import {test,expect} from '@playwright/test';
test('Connection settings verify backend, create typed images and retrieve video without storing credentials',async({page})=>{
 await page.goto('./');const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=4;return c.toDataURL().split(',')[1];});
 await page.route('https://ai.example/**',async route=>{const p=new URL(route.request().url()).pathname;const headers={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type'};if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});const json=p==='/health'?{service:'tinh-hoa-ai',ok:true,imageModel:'image-test',videoModel:'video-test'}:p==='/image'?{data:png,mimeType:'image/png'}:p==='/video'?{ticket:'test-ticket'}:{done:true,data:'eA==',mimeType:'video/mp4'};await route.fulfill({status:200,headers,contentType:'application/json',body:JSON.stringify(json)});});
 await page.locator('[data-video-mode="text"]').click();await page.locator('[data-hub-tab="new"]').click();await page.locator('#new-project-name').fill('API demo');await page.locator('#new-project-seconds').selectOption('8');await page.locator('#text-project-form button[type="submit"]').click();await expect(page.locator('#text-script')).toBeVisible();await page.locator('[data-tab="settings"]').click();await page.locator('#ai-mode').selectOption('gemini');await page.locator('#ai-url').fill('https://ai.example');await page.locator('#ai-secret').fill('private-test-token');await page.locator('#ai-check').click();await expect(page.locator('#ai-status')).toContainText('Đã kiểm tra khóa');
 expect(await page.evaluate(()=>JSON.stringify(localStorage))).not.toContain('private-test-token');await page.locator('[data-tab="prompts"]').click();page.on('dialog',d=>d.accept());
 await page.locator('[data-prompt-tab=character]').click();await page.locator('#text-character [data-ref-generate]').click();await expect(page.locator('#text-character img')).toBeVisible();await page.locator('[data-prompt-tab=context]').click();await page.locator('#text-context [data-ref-generate]').click();await expect(page.locator('#text-context img')).toBeVisible();await page.locator('[data-prompt-tab=script]').click();await expect(page.locator('[data-text-video]')).toBeVisible();await page.locator('[data-text-video]').click();await expect(page.locator('[data-text-video]')).toHaveText('Kiểm tra / nhận video');await page.locator('[data-text-video]').click();await expect(page.locator('#text-sync-result')).toContainText('Đã lưu video');
 await page.locator('[data-tab="library"]').click();await expect(page.locator('[data-asset-type]')).toHaveCount(2);expect(await page.locator('[data-asset-type]').evaluateAll(es=>es.map(e=>e.value).sort())).toEqual(['character','context']);await page.reload();await page.locator('[data-video-mode="text"]').click();await page.locator('#projects .project').click();await page.locator('[data-tab="settings"]').click();await expect(page.locator('#ai-secret')).toHaveValue('');await expect(page.locator('#ai-status')).toContainText('Chưa kết nối');
});

test('Connection setup reports failures and ignores a health response after disconnect',async({page})=>{
 await page.goto('./');await page.locator('[data-video-mode="text"]').click();await page.locator('[data-hub-tab="new"]').click();await page.locator('#new-project-name').fill('Kết nối');await page.locator('#text-project-form [type="submit"]').click();await page.locator('[data-tab="settings"]').click();
 await expect(page.locator('#ai-status')).toContainText('tab riêng');await page.locator('#ai-mode').selectOption('gemini');await expect(page.locator('#ai-status')).toContainText('chưa có địa chỉ');
 await page.locator('#ai-url').fill('http://ai.example');await page.locator('#ai-check').click();await expect(page.locator('#ai-status')).toContainText('HTTPS');
 await page.locator('#ai-url').fill('https://ai.example');await page.locator('#ai-check').click();await expect(page.locator('#ai-status')).toContainText('nhập mã');
 let pending,release,delay=false,unauthorized=true;const started=new Promise(r=>pending=r);const hold=new Promise(r=>release=r);
 await page.route('https://ai.example/**',async route=>{const headers={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type'};if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});if(delay){pending();await hold;}await route.fulfill({status:unauthorized?401:200,headers,contentType:'application/json',body:JSON.stringify(unauthorized?{error:'denied'}:{service:'tinh-hoa-ai',ok:true,imageModel:'image-test',videoModel:'video-test'})});});
 await page.locator('#ai-secret').fill('session-access');await page.locator('#ai-check').click();await expect(page.locator('#ai-status')).toContainText('Mã truy cập máy chủ không đúng');
 unauthorized=false;delay=true;await page.locator('#ai-check').click();await started;await page.locator('#ai-disconnect').click();release();await expect(page.locator('#ai-check')).toBeEnabled();await expect(page.locator('#ai-status')).toContainText('Đã ngắt kết nối');await expect(page.locator('#ai-models')).toBeHidden();await expect(page.locator('#ai-secret')).toHaveValue('');
 delay=false;await page.locator('#ai-secret').fill('session-access');await page.locator('#ai-check').click();await expect(page.locator('#ai-models')).toContainText('image-test');await expect(page.locator('#ai-status')).toContainText('chưa xác minh số dư');
 await page.locator('#ai-mode').selectOption('flow');await expect(page.locator('#ai-models')).toBeHidden();await page.locator('#ai-mode').selectOption('gemini');await expect(page.locator('#ai-secret')).toHaveValue('');expect(await page.evaluate(()=>JSON.stringify(localStorage))).not.toContain('session-access');
});
