import {test,expect} from '@playwright/test';
test('Video modes open a type sidebar with horizontal tabs and isolate project lists and restores',async({page})=>{
 await page.goto('./');await expect(page.locator('aside')).toHaveCount(0);await expect(page.locator('[data-video-mode]')).toHaveCount(4);await expect(page.locator('#new, #restore-file, #projects')).toHaveCount(0);await page.locator('[data-video-mode="text"]').click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await expect(page.locator('.project-hub h2')).toHaveText(['Tạo dự án mới','Các dự án gần đây','Khôi phục dự án']);
 const overview=await page.locator('[data-tab="overview"]').boundingBox(),library=await page.locator('[data-tab="library"]').boundingBox();expect(library.y).toBe(overview.y);expect(library.x).toBeGreaterThan(overview.x);await expect(page.locator("aside [data-video-mode]")).toHaveCount(4);await expect(page.locator("main>.tabs button")).toHaveText(["Tổng quan","Nhân vật & Bối cảnh","Prompt / Câu lệnh","Cài đặt"]);
 await expect(page.locator('[data-tab="prompts"]')).toBeDisabled();
 for(const id of ['new','restore','recent']){await page.locator('[data-hub-tab="'+id+'"]').click();await expect(page.locator('.hub-tabs button:visible')).toHaveCount(3);await expect(page.locator('.hub-section:visible')).toHaveCount(1);}
 await page.locator('[data-hub-tab=\"new\"]').click();await page.locator('#new').click();await page.getByRole('dialog').getByLabel('Tên dự án').fill('Văn bản riêng');await page.getByRole('button',{name:'Tạo dự án',exact:true}).click();await expect(page.locator('#name')).toHaveValue('Văn bản riêng');
 const dl=page.waitForEvent('download');await page.locator('#backup').click();const file=await(await dl).path();
 await page.locator('[data-video-mode="koc"]').click();await expect(page.locator('#count')).toHaveText('0');await expect(page.locator('#projects')).not.toContainText('Văn bản riêng');
 await page.locator('[data-hub-tab=\"new\"]').click();await page.locator('#new').click();await page.getByRole('dialog').getByLabel('Tên dự án').fill('KOC riêng');await page.getByRole('button',{name:'Tạo dự án',exact:true}).click();await expect(page.locator('#count')).toHaveText('1');
 const dialog=page.waitForEvent('dialog');await page.locator('#restore-file').setInputFiles(file);const alert=await dialog;expect(alert.message()).toContain('chọn đúng loại video');await alert.accept();await expect(page.locator('#count')).toHaveText('1');
 await page.locator('[data-video-mode="text"]').click();await expect(page.locator('#projects')).toContainText('Văn bản riêng');await expect(page.locator('#projects')).not.toContainText('KOC riêng');await page.locator('#restore-file').setInputFiles(file);await expect(page.locator('#count')).toHaveText('2');
 await page.locator('[data-video-mode="long"]').click();await expect(page.locator('#count')).toHaveText('0');await page.locator('[data-hub-tab=\"new\"]').click();await page.locator('#new').click();await page.getByRole('dialog').getByLabel('Tên dự án').fill('Video dài riêng');await page.getByRole('button',{name:'Tạo dự án',exact:true}).click();await page.locator('[data-tab="prompts"]').click();await expect(page.locator('[data-product="kind"]')).toHaveValue('Video dài');await expect(page.locator('[data-product="ratio"]')).toHaveValue('16:9');
});
