import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
const image={name:'SAN_PHAM.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a0d8AAAAASUVORK5CYII=','base64')};
async function create(page){await page.goto('./');await page.locator('#new').click();await page.getByRole('dialog').getByLabel('Tên dự án').fill('Thương hiệu thử');await page.getByRole('button',{name:'Tạo dự án',exact:true}).click();}
async function tab(page,name){await page.getByRole('button',{name,exact:true}).click();}
test('Brand, selected product images and draft timings survive full backup restore',async({page})=>{
 await create(page);await tab(page,'Cài đặt');await page.locator('[data-brand="name"]').fill('Tinh Hoa kiểm thử');await page.locator('#brand-logo').setInputFiles(image);await expect(page.locator('#logo-preview img')).toBeVisible();await page.locator('#save-settings').click();
 await tab(page,'Form / Câu lệnh');await page.locator('[data-product="name"]').fill('Bánh nhập khẩu');await page.locator('#brief-images').setInputFiles(image);await expect(page.locator('[data-brief-image]:checked')).toHaveCount(1);await page.locator('[data-product="duration"]').selectOption('16 giây');await page.locator('#draft-prompts').click();await expect(page.locator('.prompt-card')).toHaveCount(2);await expect(page.locator('[data-prompt-text]').first()).toContainText('Tinh Hoa kiểm thử');await expect(page.locator('.ref-selected img')).toHaveCount(2);
 await tab(page,'Tổng quan');const download=page.waitForEvent('download');await page.locator('#backup').click();const file=await (await download).path();const data=JSON.parse(await fs.readFile(file,'utf8'));expect(data.project.brand.name).toBe('Tinh Hoa kiểm thử');expect(data.project.prompts.map(p=>p.duration)).toEqual([8,8]);
 await page.locator('#restore-file').setInputFiles(file);await expect(page.locator('#name')).toHaveValue('Thương hiệu thử (khôi phục)');await tab(page,'Cài đặt');await expect(page.locator('[data-brand="name"]')).toHaveValue('Tinh Hoa kiểm thử');await expect(page.locator('#logo-preview img')).toBeVisible();await page.getByRole('button',{name:/^Form \/ Câu lệnh/}).click();await expect(page.locator('[data-brief-image]:checked')).toHaveCount(1);await expect(page.locator('.ref-selected img')).toHaveCount(2);await page.locator('[data-ready]').first().click();await page.locator('#to-video').click();await expect(page.locator('.video-card')).toHaveCount(1);
});
test('Long video divides to 300 seconds and product selection rejects an eighth image',async({page})=>{
 await create(page);await tab(page,'Form / Câu lệnh');await page.locator('#brief-images').setInputFiles(Array.from({length:7},(_,i)=>({...image,name:`SP${i}.png`})));await expect(page.locator('[data-brief-image]:checked')).toHaveCount(7);page.once('dialog',d=>d.accept());await page.locator('#brief-images').setInputFiles({...image,name:'eight.png'});await expect(page.locator('[data-brief-image]')).toHaveCount(7);
 await page.locator('[data-product="kind"]').selectOption('Video dài');await page.locator('[data-product="duration"]').selectOption('Video dài');await expect(page.locator('#long-seconds')).toBeEnabled();await page.locator('#long-seconds').fill('300');await page.locator('#long-seconds').press('Tab');await page.locator('#draft-prompts').click();await expect(page.locator('.prompt-card')).toHaveCount(38);await expect(page.locator('[data-prompt-text]').last()).toContainText('4 giây');
 const dl=page.waitForEvent('download');await page.locator('#export-scenes').click();const text=await fs.readFile(await(await dl).path(),'utf8');expect(text).toContain('Số cảnh: 38');expect(text).toContain('SP0');
});
