import {test,expect} from '@playwright/test';
test('Episodes are added on demand with shared images and isolated scripts and videos across reload and backup',async({page})=>{
 await page.goto('./');await page.locator('[data-video-mode="text"]').click();await page.locator('[data-hub-tab="new"]').click();
 await expect(page.locator('#new-series-count, #new-project-multiple')).toHaveCount(0);
 await page.locator('#new-reference-files').setInputFiles({name:'nhan-vat.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jhXcAAAAASUVORK5CYII=','base64')});
 await page.locator('#new-project-name').fill('Bộ phim Tinh Hoa');await page.locator('#new-project-idea').fill('Câu chuyện chung');await page.locator('#new-project-seconds').selectOption('16');
 await page.locator('[data-hub-tab="recent"]').click();await page.locator('[data-hub-tab="new"]').click();await expect(page.locator('#new-project-name')).toHaveValue('Bộ phim Tinh Hoa');
 await page.locator('#text-project-form button[type="submit"]').click();await expect(page.locator('[data-text-scene]')).toHaveCount(2);await expect(page.locator('[data-open-episode]')).toHaveCount(1);
 await page.locator('[data-text-scene]').first().fill('Nội dung riêng tập 1');await page.locator('#save-text-prompts').click();
 await page.locator('[data-tab="videos"]').click();await page.locator('#import-videos').setInputFiles({name:'tap-mot.webm',mimeType:'video/webm',buffer:Buffer.from('episode-one')});await expect(page.locator('.video-card')).toHaveCount(1);
 await page.locator('#episode-complete').click();await expect(page.locator('[data-open-episode]').first()).toContainText('Hoàn thành');
 await page.locator('#add-episode').click();await page.locator('#add-episode-title').fill('Tập tiếp theo');await page.locator('#add-episode-idea').fill('Khám phá vùng đất mới');await page.locator('#new-episode-form [type="submit"]').click();
 await expect(page.locator('[data-open-episode]')).toHaveCount(2);await expect(page.locator('[data-text-scene]')).toHaveCount(2);await expect(page.locator('[data-text-scene]').first()).not.toHaveValue(/Nội dung riêng tập 1/);await expect(page.locator('[data-text-scene]').first()).toHaveValue(/Khám phá vùng đất mới/);
 await page.locator('[data-text-scene]').first().fill('Nội dung riêng tập 2');await page.locator('#save-text-prompts').click();
 await page.locator('[data-tab="library"]').click();await expect(page.locator('[data-asset-name]')).toHaveValue('nhan-vat');
 await page.locator('[data-tab="videos"]').click();await expect(page.locator('.video-card')).toHaveCount(0);await page.locator('[data-open-episode]').first().click();await expect(page.locator('.video-card')).toHaveCount(1);
 await page.locator('[data-tab="prompts"]').click();await expect(page.locator('[data-text-scene]').first()).toHaveValue('Nội dung riêng tập 1');await page.locator('[data-open-episode]').nth(1).click();await expect(page.locator('[data-text-scene]').first()).toHaveValue('Nội dung riêng tập 2');
 await page.reload();await page.locator('[data-video-mode="text"]').click();await page.locator('#projects .project').first().click();await expect(page.locator('#episode-title')).toHaveValue('Tập tiếp theo');
 const dl=page.waitForEvent('download');await page.locator('#backup').click();const file=await(await dl).path();await page.locator('#restore-file').setInputFiles(file);await expect(page.locator('#name')).toHaveValue('Bộ phim Tinh Hoa (khôi phục)');await expect(page.locator('[data-open-episode]')).toHaveCount(2);
 await page.locator('[data-tab="prompts"]').click();await expect(page.locator('[data-text-scene]').first()).toHaveValue('Nội dung riêng tập 2');await page.locator('[data-open-episode]').first().click();await expect(page.locator('[data-text-scene]').first()).toHaveValue('Nội dung riêng tập 1');await page.locator('[data-tab="videos"]').click();await expect(page.locator('.video-card')).toHaveCount(1);
 await page.locator('[data-tab="overview"]').click();await page.locator('[data-hub-tab="new"]').click();await expect(page.locator('.episode-folders, #name, .episode-editor')).toHaveCount(0);
});
