import {test,expect} from '@playwright/test';
test('New text project generates editable prompt groups and gates Flow video links on persisted reference images',async({page})=>{
 await page.goto('./');await page.locator('[data-video-mode="text"]').click();await page.locator('[data-hub-tab="new"]').click();await page.locator('#new-project-name').fill('Chuyện mùa thu');await page.locator('#new-project-idea').fill('Một người đi qua khu vườn mùa thu.');await page.locator('#text-project-form button[type="submit"]').click();
 await expect(page.locator('[data-tab="prompts"]')).toHaveClass('active');await expect(page.locator('[data-ref-prompt]')).toHaveCount(3);await expect(page.locator('[data-text-scene]')).toHaveCount(5);await expect(page.locator('[data-text-video]:visible')).toHaveCount(0);await expect(page.locator('#sync-text-refs')).toBeHidden();
 await page.locator('#text-character [data-ref-prompt]').fill('Nhân vật áo xanh.');await page.locator('[data-text-scene]').first().fill('Cảnh mở đầu đã sửa.');await page.locator('#save-text-prompts').click();
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=4;c.height=4;c.getContext('2d').fillRect(0,0,4,4);return c.toDataURL().split(',')[1];});const file={name:'ref.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')};
 await page.locator('#text-character [data-ref-upload]').setInputFiles(file);await expect(page.locator('#text-character img')).toBeVisible();await expect(page.locator('[data-text-video]:visible')).toHaveCount(0);
 await page.locator('#text-context [data-ref-upload]').setInputFiles(file);await expect(page.locator('[data-text-video]:visible')).toHaveCount(5);
 await expect(page.locator('#sync-text-refs')).toBeVisible();await page.locator('#sync-text-refs').click();await page.locator('#sync-text-refs').click();await expect(page.locator('[data-text-scene]').first()).toHaveValue(/Cảnh mở đầu đã sửa\./);expect((await page.locator('[data-text-scene]').first().inputValue()).match(/\[ẢNH THAM CHIẾU\]/g)).toHaveLength(1);await page.locator('#text-product [data-ref-required]').check();await expect(page.locator('[data-text-video]:visible')).toHaveCount(0);await page.locator('#text-product [data-ref-required]').uncheck();await page.locator('#save-text-prompts').click();
 await page.locator('[data-tab="overview"]').click();await expect(page.locator('#projects')).toContainText('Chuyện mùa thu');const dl=page.waitForEvent('download');await page.locator('#backup').click();const path=await(await dl).path();await page.locator('#restore-file').setInputFiles(path);await expect(page.locator('#name')).toHaveValue('Chuyện mùa thu (khôi phục)');await page.locator('[data-tab="prompts"]').click();await expect(page.locator('#text-character [data-ref-prompt]')).toHaveValue('Nhân vật áo xanh.');await expect(page.locator('[data-text-scene]').first()).toHaveValue(/Cảnh mở đầu đã sửa\./);await expect(page.locator('[data-text-video]:visible')).toHaveCount(5);
 await page.locator('#text-context [data-ref-select]').selectOption('');await expect(page.locator('[data-text-video]:visible')).toHaveCount(0);
});
