import {test,expect} from '@playwright/test';
test('Episodes are added on demand with shared images and isolated scripts and videos across reload and backup',async({page})=>{
 await page.goto('./');await page.locator('[data-video-mode="text"]').click();await page.locator('[data-hub-tab="new"]').click();
 await expect(page.locator('#new-series-count, #new-project-multiple')).toHaveCount(0);await page.locator('#new-project-structure').selectOption('multiple');
 await page.locator('#episode-reference-files').setInputFiles({name:'nhan-vat.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jhXcAAAAASUVORK5CYII=','base64')});
 await page.locator('#new-project-name').fill('Bộ phim Tinh Hoa');await page.locator('#new-episode-idea').fill('Câu chuyện chung');await page.locator('#new-project-seconds').selectOption('16');await page.locator('#new-episode-seconds').selectOption('16');
 await page.locator('[data-hub-tab="recent"]').click();await page.locator('[data-hub-tab="new"]').click();await expect(page.locator('#new-project-name')).toHaveValue('Bộ phim Tinh Hoa');
 await page.locator('#text-project-form button[type="submit"]').click();await expect(page.locator('[data-text-scene]')).toHaveCount(2);await expect(page.locator('[data-open-episode]')).toHaveCount(1);
 await page.locator('[data-text-scene]').first().fill('Nội dung riêng tập 1');await page.locator('#save-text-prompts').click();
 await page.locator('[data-tab="videos"]').click();await page.locator('#import-videos').setInputFiles({name:'tap-mot.webm',mimeType:'video/webm',buffer:Buffer.from('episode-one')});await expect(page.locator('.video-card')).toHaveCount(1);
 await page.locator('#episode-complete').click();await expect(page.locator('[data-open-episode]').first()).toContainText('Hoàn thành');
 await page.locator('#add-episode').click();await page.locator('#add-episode-title').fill('Tập tiếp theo');await page.locator('#add-episode-idea').fill('Khám phá vùng đất mới');await page.locator('#new-episode-form [type="submit"]').click();
 await expect(page.locator('[data-open-episode]')).toHaveCount(2);await expect(page.locator('[data-text-scene]')).toHaveCount(2);await expect(page.locator('[data-text-scene]').first()).not.toHaveValue(/Nội dung riêng tập 1/);await expect(page.locator('[data-text-scene]').first()).toHaveValue(/Khám phá vùng đất mới/);
 await page.locator('[data-text-scene]').first().fill('Nội dung riêng tập 2');await page.locator('#save-text-prompts').click();
 await page.locator('[data-tab="library"]').click();await expect(page.locator('[data-asset-name]')).toHaveValue('nhan-vat');
 await page.locator('[data-tab="videos"]').click();await expect(page.locator('.video-card')).toHaveCount(0);await page.locator('[data-open-episode]').first().click();await expect(page.locator('.video-card')).toHaveCount(1);
 await page.locator('[data-tab="prompts"]').click();await expect(page.locator('[data-text-scene]').first()).toHaveValue('Nội dung riêng tập 1');await page.locator('[data-open-episode]').nth(1).click();await expect(page.locator('[data-text-scene]').first()).toHaveValue('Nội dung riêng tập 2');
 await page.reload();await page.locator('[data-video-mode="text"]').click();await page.locator('#projects .project').first().click();await expect(page.locator('#episode-title')).toHaveValue('Tập tiếp theo');
 const dl=page.waitForEvent('download');await page.locator('#backup').click();const file=await(await dl).path();await page.locator('#restore-file').setInputFiles(file);await expect(page.locator('#name')).toHaveValue('Bộ phim Tinh Hoa (khôi phục)');await expect(page.locator('[data-open-episode]')).toHaveCount(2);
 await page.locator('[data-tab="prompts"]').click();await expect(page.locator('[data-text-scene]').first()).toHaveValue('Nội dung riêng tập 2');await page.locator('[data-open-episode]').first().click();await expect(page.locator('[data-text-scene]').first()).toHaveValue('Nội dung riêng tập 1');await page.locator('[data-tab="videos"]').click();await expect(page.locator('.video-card')).toHaveCount(1);
 await page.locator('[data-tab="overview"]').click();await page.locator('[data-hub-tab="new"]').click();await expect(page.locator('.episode-folders, #name, .episode-editor')).toHaveCount(0);
});

test('Single and multiple forms retain their own drafts and episode settings survive restore',async({page})=>{
 await page.goto('./');await page.locator('[data-video-mode="text"]').click();await page.locator('[data-hub-tab="new"]').click();await expect(page.locator('#new-project-structure')).toHaveValue('single');await expect(page.locator('#first-episode-fields')).toBeHidden();await page.locator('#new-project-name').fill('Phim nhiều tập');await page.locator('#new-project-idea').fill('Ý tưởng một tập');await page.locator('#new-project-seconds').selectOption('40');
 await page.locator('#new-project-structure').selectOption('multiple');await expect(page.locator('#project-idea-fields')).toBeHidden();await expect(page.locator('#project-image-fields')).toBeHidden();await page.locator('#new-episode-title').fill('Hành trình đầu tiên');await page.locator('#new-episode-idea').fill('Khởi hành lên núi');await page.locator('#new-episode-seconds').selectOption('16');await page.locator('#new-episode-ratio').selectOption('16:9');await page.locator('#new-episode-style').selectOption('Anime');
 await page.locator('#new-project-structure').selectOption('single');await expect(page.locator('#new-project-idea')).toHaveValue('Ý tưởng một tập');await page.locator('#new-project-structure').selectOption('multiple');await expect(page.locator('#new-episode-idea')).toHaveValue('Khởi hành lên núi');
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=4;return c.toDataURL().split(',')[1];});await page.locator('#episode-reference-files').setInputFiles({name:'tap-1.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.locator('#text-project-form [type="submit"]').click();await expect(page.locator('[data-open-episode]')).toContainText('Hành trình đầu tiên');await expect(page.locator('[data-text-scene]')).toHaveCount(2);await expect(page.locator('[data-text-scene]').first()).toHaveValue(/Khởi hành lên núi/);await expect(page.locator('[data-text-scene]').first()).not.toHaveValue(/Ý tưởng một tập/);await expect(page.locator('#text-character [data-ref-select]')).not.toHaveValue('');
 await page.locator('#add-episode').click();await page.locator('#add-episode-title').fill('Phần hai');await page.locator('#add-episode-seconds').selectOption('8');await page.locator('#add-episode-ratio').selectOption('9:16');await page.locator('#new-episode-form [type="submit"]').click();await expect(page.locator('[data-text-scene]')).toHaveCount(1);await expect(page.locator('#text-character [data-ref-select]')).toHaveValue('');await page.locator('[data-open-episode]').first().click();await expect(page.locator('[data-text-scene]')).toHaveCount(2);await expect(page.locator('#text-character [data-ref-select]')).not.toHaveValue('');
 await page.locator('[data-tab="overview"]').click();const dl=page.waitForEvent('download');await page.locator('#backup').click();const file=await(await dl).path();await page.locator('#restore-file').setInputFiles(file);await expect(page.locator('#name')).toHaveValue('Phim nhiều tập (khôi phục)');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('tinh-hoa.projects.v1')).find(p=>p.name.endsWith('(khôi phục)')));expect(saved.projectStructure).toBe('multiple');expect(saved.episodes[0].settings).toMatchObject({ratio:'16:9',seconds:16,style:'Anime'});expect(saved.episodes[1].settings.seconds).toBe(8);expect(saved.episodes[0].referencePrompts.find(r=>r.type==='character').assetId).toBe(saved.episodes[0].referenceImageIds[0]);
 await page.locator('[data-hub-tab="new"]').click();await page.locator('#new-project-name').fill('Video riêng');await page.locator('#new-project-idea').fill('Nội dung dự án riêng');await page.locator('#text-project-form [type="submit"]').click();await expect(page.locator('.episode-folders')).toHaveCount(0);await expect(page.locator('[data-text-scene]').first()).toHaveValue(/Nội dung dự án riêng/);
});
