import {test,expect} from '@playwright/test';
test('Inline text creation retains series ideas across navigation, reload and backup',async({page})=>{
 await page.goto('./');await page.locator('[data-video-mode="text"]').click();await page.locator('[data-hub-tab="new"]').click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await page.locator('#new-reference-files').setInputFiles({name:'nhan-vat.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jhXcAAAAASUVORK5CYII=','base64')});await expect(page.locator('.new-reference-card')).toHaveCount(1);await page.locator('[data-reference-type]').selectOption('product');
 await page.locator('#new-project-name').fill('Bộ phim Tinh Hoa');await page.locator('#new-project-idea').fill('Câu chuyện chung');
 await page.locator('#new-project-ratio').selectOption('16:9');await page.locator('#new-project-seconds').selectOption('180');await page.locator('#new-project-style').selectOption('Điện ảnh');await page.locator('#new-project-multiple').check();await page.locator('#new-series-count').fill('3');await page.locator('#new-series-count').press('Tab');
 await page.locator('[data-draft-title="0"]').fill('Khởi đầu');await page.locator('[data-draft-idea="0"]').fill('Ý tưởng tập một');
 await page.locator('[data-hub-tab="recent"]').click();await page.locator('[data-hub-tab="new"]').click();await expect(page.locator('#new-project-name')).toHaveValue('Bộ phim Tinh Hoa');await expect(page.locator('[data-draft-idea="0"]')).toHaveValue('Ý tưởng tập một');
 await page.locator('#text-project-form button[type="submit"]').click();await expect(page.locator('[data-tab="prompts"]')).toHaveClass('active');await page.locator('[data-tab="overview"]').click();await expect(page.locator('#name')).toHaveValue('Bộ phim Tinh Hoa');await expect(page.locator('#notes')).toHaveValue('Câu chuyện chung');await expect(page.locator('[data-episode-title]')).toHaveCount(3);
 await expect(page.locator('#asset-count')).toHaveText('1');await page.locator('[data-episode-idea="1"]').fill('Nội dung tập hai');await page.locator('#save').click();await page.reload();await page.locator('[data-video-mode="text"]').click();await page.locator('#projects .project').first().click();await expect(page.locator('[data-episode-idea="1"]')).toHaveValue('Nội dung tập hai');
 const dl=page.waitForEvent('download');await page.locator('#backup').click();const file=await(await dl).path();await page.locator('#restore-file').setInputFiles(file);await expect(page.locator('#name')).toHaveValue('Bộ phim Tinh Hoa (khôi phục)');
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('tinh-hoa.projects.v1')).find(p=>p.name==='Bộ phim Tinh Hoa (khôi phục)'));expect(saved.product.ratio).toBe('16:9');expect(saved.product.duration).toBe('Video dài');expect(Number(saved.product.longSeconds)).toBe(180);expect(saved.brand.style).toBe('Điện ảnh');await expect(page.locator('[data-episode-idea="1"]')).toHaveValue('Nội dung tập hai');
 await page.locator('[data-tab="library"]').click();await expect(page.locator('[data-asset-name]')).toHaveValue('nhan-vat');await expect(page.locator('[data-asset-type]')).toHaveValue('product');await page.locator('[data-tab="overview"]').click();await page.locator('[data-hub-tab="new"]').click();await expect(page.locator('#name, #notes, .stats, .episode-editor')).toHaveCount(0);await expect(page.locator('.new-reference-card')).toHaveCount(0);await page.locator('#new-project-name').fill('Một video');await page.locator('#new-project-idea').fill('Ý tưởng độc lập');await expect(page.locator('#new-project-multiple')).not.toBeChecked();await page.locator('#text-project-form button[type="submit"]').click();await expect(page.locator('[data-tab="prompts"]')).toHaveClass('active');await page.locator('[data-tab="overview"]').click();await expect(page.locator('#name')).toHaveValue('Một video');await expect(page.locator('[data-episode-title]')).toHaveCount(0);
});
