import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function create(page){await page.goto('./');await page.locator('[data-video-mode="product"]').click();await page.locator('[data-hub-tab=\"new\"]').click();await page.getByRole('button',{name:'＋ Tạo dự án',exact:true}).click();await page.getByRole('dialog').getByLabel('Tên dự án',{exact:true}).fill('Kiểm tra quy trình');await page.getByRole('button',{name:'Tạo dự án',exact:true}).click();}
test('Nhập cảnh, chọn nhiều ảnh, sao lưu và khôi phục đầy đủ sau tải lại',async({page})=>{
 await create(page);await page.getByRole('button',{name:'Nhân vật & Bối cảnh',exact:true}).click();
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9i0AAAAASUVORK5CYII=','base64');
 await page.locator('#asset-files').setInputFiles([{name:'KOC_ANNA.png',mimeType:'image/png',buffer:png},{name:'SHOWROOM.png',mimeType:'image/png',buffer:png}]);
 await expect(page.locator('.asset-card')).toHaveCount(2);await page.getByRole('button',{name:'Prompt / Câu lệnh'}).click();
 await page.locator('#batch-prompts').fill('KOC_ANNA đứng trong SHOWROOM.\nCận sản phẩm.');await page.locator('#import-prompts').click();await expect(page.locator('.prompt-card')).toHaveCount(2);await page.locator('#sync-refs').click();await expect(page.locator('.prompt-card').first().locator('.ref-selected img')).toHaveCount(2);
 await page.locator('[data-tab=\"overview\"]').click();await page.getByRole('button',{name:'Video',exact:true}).click();await page.locator('#import-videos').setInputFiles('tests/fixtures/clip.webm');await expect(page.locator('.video-card video')).toHaveCount(1);
 await page.getByRole('button',{name:'Tổng quan',exact:true}).click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Sao lưu đầy đủ'}).click();const dl=await downloadPromise;const backup=await readFile(await dl.path());
 await page.locator('#restore-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:backup});await expect(page.locator('#count')).toHaveText('2');await page.reload();await page.locator('[data-video-mode="product"]').click();await page.locator('#projects .project').filter({hasText:'(khôi phục)'}).click();await page.getByRole('button',{name:'Prompt / Câu lệnh'}).click();await expect(page.locator('.prompt-card').first().locator('.ref-selected img')).toHaveCount(2);
 await page.locator('[data-tab=\"overview\"]').click();await page.getByRole('button',{name:'Video',exact:true}).click();await expect(page.locator('.video-card video')).toHaveCount(1);await expect.poll(()=>page.locator('.video-card video').evaluate(v=>v.readyState)).toBeGreaterThan(0);
});
test('Nhập hai clip, đổi thứ tự, ghép thật và lưu kết quả sau reload',async({page})=>{
 await create(page);await page.locator('[data-tab="settings"]').click();const logo=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=32;const x=c.getContext('2d');x.fillStyle='#ff0000';x.fillRect(0,0,32,32);return c.toDataURL().split(',')[1];});await page.locator('#brand-logo').setInputFiles({name:'red.png',mimeType:'image/png',buffer:Buffer.from(logo,'base64')});await expect(page.locator('#logo-preview img')).toBeVisible();await page.locator('#logo-enabled').check();await page.locator('#logo-position').selectOption('top-left');await page.locator('#logo-opacity').fill('100');await page.locator('#logo-opacity').press('Tab');await page.locator('#save-settings').click();await page.locator('[data-tab=\"overview\"]').click();await page.getByRole('button',{name:'Video',exact:true}).click();const buffer=await readFile('tests/fixtures/clip.webm');await page.locator('#import-videos').setInputFiles([{name:'A.webm',mimeType:'video/webm',buffer},{name:'B.webm',mimeType:'video/webm',buffer}]);await expect(page.locator('.video-card video')).toHaveCount(2);await page.getByRole('button',{name:'Đưa cảnh 2 lên'}).click();await expect(page.locator('.video-card').first()).toContainText('B.webm');await page.locator('#merge-videos').click();await expect(page.locator('#merged-output')).toBeVisible({timeout:30000});await expect.poll(()=>page.locator('#merged-output video').evaluate(v=>v.readyState)).toBeGreaterThan(0);
 const pixel=await page.locator('#merged-output video').evaluate(async v=>{v.currentTime=.3;await new Promise(r=>v.addEventListener('seeked',r,{once:true}));const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);return [...c.getContext('2d').getImageData(40,40,1,1).data];});expect(pixel[0]).toBeGreaterThan(180);expect(pixel[1]).toBeLessThan(70);expect(pixel[2]).toBeLessThan(70);
 const download=page.waitForEvent('download');await page.locator('#download-merged').click();expect((await download).suggestedFilename()).toBe('tinh-hoa-ghep.webm');await page.reload();await page.locator('[data-video-mode="product"]').click();await page.locator('#projects .project').first().click();await page.locator('[data-tab=\"overview\"]').click();await page.getByRole('button',{name:'Video',exact:true}).click();await expect(page.locator('#merged-output')).toBeVisible();
});
