import http from 'node:http';
import {createHmac,timingSafeEqual} from 'node:crypto';
import {pathToFileURL} from 'node:url';
const API='https://generativelanguage.googleapis.com/v1beta/';
export function createAiServer(env=process.env,request=fetch){
 const key=env.GEMINI_API_KEY,token=env.AI_ACCESS_TOKEN,origin=env.APP_ORIGIN,imageModel=env.IMAGE_MODEL||'gemini-2.5-flash-image',videoModel=env.VIDEO_MODEL||'veo-3.1-generate-preview';
 if(!key||!token||token.length<32||!origin)throw Error('Set GEMINI_API_KEY, AI_ACCESS_TOKEN (32+ characters), APP_ORIGIN.');
 const equal=(a,b)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);};
 const sign=v=>createHmac('sha256',token).update(v).digest('base64url');
 const ticket=name=>{const s=Buffer.from(JSON.stringify({name,expires:Date.now()+47*3600000})).toString('base64url');return s+'.'+sign(s);};
 const readTicket=s=>{const [v,sig]=s.split('.');if(!v||!sig||!equal(sig,sign(v)))throw Error('Tác vụ không hợp lệ.');const d=JSON.parse(Buffer.from(v,'base64url'));if(d.expires<Date.now()||!/^models\/[\w.-]+\/operations\/[\w.-]+$/.test(d.name))throw Error('Tác vụ hết hạn hoặc không hợp lệ.');return d.name;};
 async function google(path,body){const r=await request(API+path,{method:body?'POST':'GET',headers:{'x-goog-api-key':key,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(150000)});const d=await r.json();if(!r.ok)throw Error(`Google API ${r.status}: ${String(d.error?.message||'Yêu cầu thất bại').replaceAll(key,'[hidden]')}`);return d;}
 async function download(uri){let u=new URL(uri);for(let i=0;i<5;i++){if(u.protocol!=='https:'||!(u.hostname==='generativelanguage.googleapis.com'||u.hostname==='storage.googleapis.com'||u.hostname.endsWith('.googleusercontent.com')))throw Error('Địa chỉ video không hợp lệ.');const r=await request(u,{headers:u.hostname==='generativelanguage.googleapis.com'?{'x-goog-api-key':key}:{},redirect:'manual',signal:AbortSignal.timeout(150000)});if(r.status>=300&&r.status<400){u=new URL(r.headers.get('location'),u);continue;}if(!r.ok)throw Error('Không tải được video từ Google.');const chunks=[];let size=0;for await(const chunk of r.body){size+=chunk.length;if(size>100*1024*1024)throw Error('Video vượt quá 100 MB.');chunks.push(chunk);}return Buffer.concat(chunks).toString('base64');}throw Error('Không tải được video.');}
 let active=false;
 return http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('Vary','Origin');if(req.headers.origin===origin){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Allow-Headers','Authorization, Content-Type');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');}const send=(code,d)=>{res.writeHead(code,{'Content-Type':'application/json'});res.end(JSON.stringify(d));};
 if(req.headers.origin&&req.headers.origin!==origin)return send(403,{error:'Nguồn truy cập không được phép.'});if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}if(!equal(req.headers.authorization||'','Bearer '+token))return send(401,{error:'Mã truy cập máy chủ không đúng.'});
 const path=new URL(req.url,'http://localhost').pathname;let acquired=false;
 try{if(req.method==='GET'&&path==='/health'){await google('models/'+imageModel);await google('models/'+videoModel);return send(200,{service:'tinh-hoa-ai',ok:true,imageModel,videoModel});}
 if(req.method==='GET'&&path.startsWith('/jobs/')){const d=await google(readTicket(decodeURIComponent(path.slice(6))));if(d.error)throw Error(d.error.message||'Google không tạo được video.');if(!d.done)return send(200,{done:false});const uri=d.response?.generateVideoResponse?.generatedSamples?.[0]?.video?.uri;if(!uri)throw Error('Không có video trả về. Kiểm tra nội dung hoặc bộ lọc của Google.');return send(200,{done:true,data:await download(uri),mimeType:'video/mp4'});}
 if(req.method!=='POST'||!['/image','/video'].includes(path))return send(404,{error:'Không có chức năng này.'});if(active)return send(429,{error:'Máy chủ đang tạo nội dung. Chờ tác vụ trước hoàn tất.'});active=true;acquired=true;
 let raw='',size=0;for await(const c of req){size+=c.length;if(size>45*1024*1024)throw Error('Dữ liệu vượt quá 45 MB.');raw+=c;}const b=JSON.parse(raw);if(typeof b.prompt!=='string'||!b.prompt.trim()||b.prompt.length>50000)throw Error('Câu lệnh rỗng hoặc quá dài.');const images=b.images||[];if(!Array.isArray(images)||images.length>3||images.some(x=>!['image/png','image/jpeg','image/webp'].includes(x.mimeType)||typeof x.data!=='string'||x.data.length>14*1024*1024||!/^[A-Za-z0-9+/]+=*$/.test(x.data)))throw Error('Ảnh tham chiếu không hợp lệ.');
 if(path==='/image'){const d=await google('models/'+imageModel+':generateContent',{contents:[{parts:[{text:b.prompt},...images.map(inlineData=>({inlineData}))]}],generationConfig:{responseModalities:['TEXT','IMAGE']}});const image=d.candidates?.[0]?.content?.parts?.find(p=>p.inlineData)?.inlineData;if(!image)throw Error('Google chưa trả về ảnh. Hãy kiểm tra câu lệnh.');return send(200,image);}
 if(!images.length||!['9:16','16:9'].includes(b.ratio)||b.seconds!==8)throw Error('Video tham chiếu yêu cầu 1–3 ảnh, khung 9:16 hoặc 16:9 và cảnh 8 giây.');const d=await google('models/'+videoModel+':predictLongRunning',{instances:[{prompt:b.prompt,referenceImages:images.map(inlineData=>({image:{inlineData},referenceType:'asset'}))}],parameters:{aspectRatio:b.ratio,durationSeconds:8,resolution:'720p'}});if(!d.name)throw Error('Google chưa trả mã tác vụ.');return send(200,{ticket:ticket(d.name)});
 }catch(e){send(400,{error:String(e.message).replaceAll(key,'[hidden]')});}finally{if(acquired)active=false;}});
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)createAiServer().listen(Number(process.env.PORT)||8787,()=>console.log('Tinh Hoa AI server ready'));
