import {basicEpisodeFields} from './text-project.js';
// Episode metadata stays on the project; shared reference images are never copied.
export function ensureEpisodes(p){
 if(p.product?.kind!=='Video từ văn bản')return false;
 let changed=false;
 if(!p.episodes?.length){p.episodes=[{id:crypto.randomUUID(),title:'Tập 1',idea:'',status:'draft'}];changed=true;}
 for(const e of p.episodes){if(!e.id){e.id=crypto.randomUUID();changed=true;}if(!e.status){e.status='draft';changed=true;}}
 if(!p.episodes.some(e=>e.id===p.activeEpisodeId)){p.activeEpisodeId=p.episodes[0].id;changed=true;}
 for(const s of p.prompts){if(!p.episodes.some(e=>e.id===s.episodeId)){const e=p.episodes.find(e=>s.title?.startsWith(e.title+' · '))||p.episodes[0];s.episodeId=e.id;changed=true;}}
 for(const v of p.videos){if(!p.episodes.some(e=>e.id===v.episodeId)){v.episodeId=p.prompts.find(s=>s.id===v.promptId)?.episodeId||p.episodes[0].id;changed=true;}}
 return changed;
}
export function episodeWorkspace(p){
 if(p.product?.kind!=='Video từ văn bản')return {view:p,commit(){}};
 const e=p.episodes.find(e=>e.id===p.activeEpisodeId),view={...p,episodes:[],episodeId:e.id,notes:[p.notes,e.idea].filter(Boolean).join('\n'),prompts:p.prompts.filter(s=>s.episodeId===e.id),videos:p.videos.filter(v=>v.episodeId===e.id)};
 view.episodeSettings=!!e.settings;
 if(e.settings){view.product={...p.product,ratio:e.settings.ratio,duration:e.settings.seconds<=60?e.settings.seconds+' giây':'Video dài',longSeconds:e.settings.seconds,sceneSeconds:e.settings.sceneSeconds||p.product.sceneSeconds};view.brand={...p.brand,style:e.settings.style};}
 Object.defineProperty(view,'referencePrompts',{get:()=>e.settings?e.referencePrompts:p.referencePrompts,set:v=>{if(e.settings)e.referencePrompts=v;else p.referencePrompts=v;},enumerable:true});
 return {view,commit(){if(e.settings){e.settings={ratio:view.product.ratio,seconds:view.product.duration==='Video dài'?Number(view.product.longSeconds):parseInt(view.product.duration)||40,sceneSeconds:Number(view.product.sceneSeconds)||8,style:view.brand.style};p.brand={...view.brand,style:p.brand.style};p.product={...view.product,ratio:p.product.ratio,duration:p.product.duration,longSeconds:p.product.longSeconds,sceneSeconds:p.product.sceneSeconds};}for(const key of ['prompts','videos'])p[key]=[...p[key].filter(s=>s.episodeId!==e.id),...view[key].map(s=>({...s,episodeId:e.id}))];}};
}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function episodeFolders(p){if(p.product?.kind!=='Video từ văn bản'||p.projectStructure==='single')return '';const e=p.episodes.find(e=>e.id===p.activeEpisodeId);return `<section class="episode-folders" aria-label="Các tập trong dự án"><div class="section-title"><div><strong>${esc(p.name)}</strong><p>Thư viện ảnh chung · Nội dung và video riêng cho từng tập</p></div><button id="episode-complete">${e.status==='done'?'Mở lại tập để chỉnh sửa':'Đánh dấu tập hoàn thành'}</button></div><nav class="episode-folder-list" aria-label="Chọn tập">${p.episodes.map(e=>`<button data-open-episode="${e.id}" aria-pressed="${e.id===p.activeEpisodeId}" class="${e.id===p.activeEpisodeId?'active':''}"><span aria-hidden="true">▱</span><strong>${esc(e.title||'Chưa đặt tên')}</strong><small>${e.status==='done'?'✓ Hoàn thành':'Đang làm'}</small></button>`).join('')}<button id="add-episode">＋ Thêm ${p.seriesKind==='products'?'sản phẩm':'tập'} mới</button></nav><form id="new-episode-form" class="card" hidden><h2>Thêm nội dung tiếp theo</h2><label>Tên tập / sản phẩm<input id="add-episode-title" maxlength="120" required value="${p.seriesKind==='products'?'Sản phẩm':'Tập'} ${p.episodes.length+1}"></label><label>Ý tưởng của tập mới<textarea id="add-episode-idea" rows="4" maxlength="20000" placeholder="Nội dung riêng của tập này…"></textarea></label>${basicEpisodeFields('add-episode',{ratio:p.product.ratio,seconds:p.product.duration==='Video dài'?p.product.longSeconds:parseInt(p.product.duration)||40,style:p.brand.style})}<fieldset class="basic-settings"><legend>Ảnh nhân vật / sản phẩm của tập mới</legend><p>Chọn ảnh đã có trong thư viện chung hoặc thêm ảnh mới.</p><div id="add-episode-existing-images" class="ref-options"></div><label>Thêm ảnh mới<input id="add-episode-reference-files" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><div id="add-episode-reference-list" class="new-reference-list"></div></fieldset><p>Các prompt, video của tập trước được giữ nguyên.</p><div class="actions"><button class="primary" type="submit">Tạo tập và mở prompt</button><button type="button" id="cancel-episode">Hủy</button></div><p id="episode-error" role="alert"></p></form></section>`;}
