const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sets={language:['Tiếng Việt','Tiếng Anh','Tiếng Trung','Tiếng Nhật','Tiếng Hàn','Tiếng Pháp'],style:['Chân thực','Điện ảnh','Hoạt hình 2D','Hoạt hình 3D','Anime','Tài liệu','Sang trọng','Tối giản','Kem – trắng – vàng kim, ánh sáng sáng rõ, sang trọng.'],music:['Không yêu cầu nhạc nền','Không nhạc nền','Piano nhẹ','Nhạc không lời thư giãn','Nhạc điện ảnh','Nhạc vui tươi','Nhạc sôi động','Âm thanh tự nhiên']};
const attrs={gender:['Nữ','Nam','Trung tính'],region:['Miền Bắc','Miền Trung','Miền Nam','Không chỉ định vùng miền'],age:['30–35 tuổi','18–25 tuổi','25–30 tuổi','35–50 tuổi','Trên 50 tuổi'],speed:['Vừa','Chậm','Nhanh'],emotion:['Ấm áp, tự nhiên','Vui tươi','Truyền cảm','Trang trọng','Năng động','Trầm lắng']};
const labels={gender:'Giới tính giọng',region:'Vùng miền',age:'Độ tuổi giọng',speed:'Tốc độ đọc',emotion:'Cảm xúc'};
const avoids=['Không méo hình','Không thay đổi nhân vật','Không thay đổi nhãn sản phẩm','Không chữ lỗi','Không watermark','Không nhấp nháy','Không rung máy','Không thêm người ngoài ý muốn'];
const defaultVoice='Nữ miền Bắc, 30–35 tuổi; giọng ấm, rõ, tự nhiên, tốc độ vừa; nhất quán giữa các cảnh.';
const select=(id,values,value)=>`<select id="${id}">${values.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`;
function voiceConfig(b){let v;try{v=JSON.parse(b.voiceOptions);}catch{}return {mode:b.voice===defaultVoice?'Chọn theo thuộc tính':b.voice==='Không lời thoại'?'Không lời thoại':'Tùy chỉnh',gender:'Nữ',region:'Miền Bắc',age:'30–35 tuổi',speed:'Vừa',emotion:'Ấm áp, tự nhiên',...v};}
export function preferencesView(b){const v=voiceConfig(b);const parts=b.negative==='Không méo hình, không thay đổi nhân vật hoặc nhãn sản phẩm.'?avoids.slice(0,3):String(b.negative||'').split('; ').filter(Boolean);return `<div class="form-grid"><label>Giọng thoại${select('voice-mode',['Chọn theo thuộc tính','Không lời thoại','Tùy chỉnh'],v.mode)}</label></div><div id="voice-attributes" class="form-grid" ${v.mode==='Chọn theo thuộc tính'?'':'hidden'}>${Object.entries(attrs).map(([k,values])=>`<label>${labels[k]}${select('voice-'+k,values,v[k])}</label>`).join('')}</div><label id="voice-custom-wrap" ${v.mode==='Tùy chỉnh'?'':'hidden'}>Mô tả giọng riêng<textarea id="voice-custom">${esc(b.voice)}</textarea></label><div class="form-grid">${Object.entries(sets).map(([key,values])=>{const custom=!values.includes(b[key]);return `<div><label>${{language:'Ngôn ngữ lời thoại',style:'Phong cách video',music:'Nhạc nền & âm thanh'}[key]}${select('choice-'+key,[...values,'Tùy chỉnh'],custom?'Tùy chỉnh':b[key])}</label><label id="custom-wrap-${key}" ${custom?'':'hidden'}>Nội dung tùy chỉnh<textarea data-choice-custom="${key}">${custom?esc(b[key]):''}</textarea></label></div>`;}).join('')}</div><fieldset class="avoid-options"><legend>Nội dung / chi tiết cần tránh</legend>${avoids.map((a,i)=>`<label><input type="checkbox" data-avoid="${i}" ${parts.includes(a)?'checked':''}>${a}</label>`).join('')}<label class="avoid-custom">Bổ sung khác<input id="avoid-custom" value="${esc(parts.filter(x=>!avoids.includes(x)).join('; '))}" placeholder="Nhập yêu cầu khác nếu cần"></label></fieldset>`;}
export function bindPreferences(b,changed){if(!document.querySelector('#voice-mode'))return;const v=voiceConfig(b);
 const updateVoice=()=>{v.mode=document.querySelector('#voice-mode').value;for(const k of Object.keys(attrs))v[k]=document.querySelector('#voice-'+k).value;document.querySelector('#voice-attributes').hidden=v.mode!=='Chọn theo thuộc tính';document.querySelector('#voice-custom-wrap').hidden=v.mode!=='Tùy chỉnh';b.voiceOptions=JSON.stringify(v);b.voice=v.mode==='Không lời thoại'?'Không lời thoại':v.mode==='Tùy chỉnh'?document.querySelector('#voice-custom').value:`${v.gender}, ${v.region}, ${v.age}; tốc độ ${v.speed.toLowerCase()}; ${v.emotion.toLowerCase()}; giữ giọng nhất quán giữa các cảnh.`;changed();};
 for(const id of ['voice-mode',...Object.keys(attrs).map(k=>'voice-'+k)])document.querySelector('#'+id).onchange=updateVoice;document.querySelector('#voice-custom').oninput=updateVoice;
 for(const key of Object.keys(sets)){const sel=document.querySelector('#choice-'+key),input=document.querySelector('[data-choice-custom="'+key+'"]');sel.onchange=()=>{document.querySelector('#custom-wrap-'+key).hidden=sel.value!=='Tùy chỉnh';b[key]=sel.value==='Tùy chỉnh'?input.value:sel.value;changed();};input.oninput=()=>{b[key]=input.value;changed();};}
 const updateAvoid=()=>{b.negative=[...document.querySelectorAll('[data-avoid]:checked')].map(el=>avoids[Number(el.dataset.avoid)]).concat(document.querySelector('#avoid-custom').value.trim()||[]).join('; ');changed();};document.querySelectorAll('[data-avoid]').forEach(el=>el.onchange=updateAvoid);document.querySelector('#avoid-custom').oninput=updateAvoid;
}
