const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({name:'',notes:'',multiple:false,kind:'series',episodes:[{title:'',idea:''},{title:'',idea:''}]});
let draft=fresh();
const episodeRows=(rows,prefix)=>rows.map((e,i)=>`<article class="episode-row"><strong>${i+1}</strong><div><label>Tên tập / sản phẩm ${i+1}<input maxlength="120" data-${prefix}-title="${i}" value="${escape(e.title)}" placeholder="Ví dụ: Tập ${i+1} hoặc tên sản phẩm"></label><label>Ý tưởng riêng ${i+1}<textarea maxlength="20000" data-${prefix}-idea="${i}" rows="3" placeholder="Nội dung dành riêng cho tập hoặc sản phẩm này">${escape(e.idea)}</textarea></label></div></article>`).join('');
export function textProjectForm(disabled){return `<form id="text-project-form" class="text-project-form"><h2>Tạo dự án mới</h2><label for="new-project-name">Tên dự án</label><input id="new-project-name" maxlength="120" required value="${escape(draft.name)}" placeholder="Đặt tên cho dự án của anh"><label for="new-project-idea">Nội dung ý tưởng dự án</label><textarea id="new-project-idea" maxlength="50000" rows="6" placeholder="Nhập câu chuyện, kịch bản hoặc ý tưởng tổng thể…">${escape(draft.notes)}</textarea><label class="series-toggle"><input id="new-project-multiple" type="checkbox" ${draft.multiple?'checked':''}>Dự án nhiều tập / nhiều sản phẩm</label><div id="new-series-options" ${draft.multiple?'':'hidden'}><p>Mỗi tập hoặc sản phẩm có tên và ý tưởng riêng trong cùng một dự án.</p><div class="form-grid"><label>Kiểu dự án<select id="new-series-kind"><option value="series" ${draft.kind==='series'?'selected':''}>Phim / video nhiều tập</option><option value="products" ${draft.kind==='products'?'selected':''}>Nhóm nhiều sản phẩm</option></select></label><label>Số tập / sản phẩm<input id="new-series-count" type="number" min="2" max="50" value="${draft.episodes.length}"></label></div><p>Từ 2 đến 50 mục. Có thể sửa nội dung từng mục sau khi tạo.</p><div id="new-episode-list">${episodeRows(draft.episodes,'draft')}</div></div><p id="new-project-error" role="alert"></p><button class="primary" type="submit" ${disabled?'disabled':''}>Tạo dự án</button></form>`;}
export function bindTextProject(onCreate){
 const form=document.querySelector('#text-project-form');if(!form)return;
 form.querySelector('#new-project-name').oninput=e=>draft.name=e.target.value;
 form.querySelector('#new-project-idea').oninput=e=>draft.notes=e.target.value;
 const count=form.querySelector('#new-series-count');
 form.querySelector('#new-project-multiple').onchange=e=>{draft.multiple=e.target.checked;form.querySelector('#new-series-options').hidden=!draft.multiple;count.disabled=!draft.multiple;};
 count.disabled=!draft.multiple;
 form.querySelector('#new-series-kind').onchange=e=>draft.kind=e.target.value;
 const bindRows=()=>{form.querySelectorAll('[data-draft-title]').forEach(el=>el.oninput=e=>draft.episodes[Number(el.dataset.draftTitle)].title=e.target.value);form.querySelectorAll('[data-draft-idea]').forEach(el=>el.oninput=e=>draft.episodes[Number(el.dataset.draftIdea)].idea=e.target.value);};
 count.onchange=()=>{if(!count.checkValidity())return;const n=Number(count.value);if(n<draft.episodes.length&&draft.episodes.slice(n).some(e=>e.title||e.idea)&&!confirm('Giảm số mục sẽ bỏ nội dung các mục cuối. Tiếp tục?')){count.value=draft.episodes.length;return;}draft.episodes=Array.from({length:n},(_,i)=>draft.episodes[i]||{title:'',idea:''});form.querySelector('#new-episode-list').innerHTML=episodeRows(draft.episodes,'draft');bindRows();};
 bindRows();
 form.onsubmit=e=>{e.preventDefault();const error=form.querySelector('#new-project-error');if(!draft.name.trim()){error.textContent='Vui lòng nhập tên dự án.';return;}const episodes=draft.multiple?draft.episodes.map((r,i)=>({id:crypto.randomUUID(),title:r.title.trim()||`${draft.kind==='products'?'Sản phẩm':'Tập'} ${i+1}`,idea:r.idea})):[];if(onCreate({name:draft.name.trim(),notes:draft.notes,seriesKind:draft.multiple?draft.kind:'single',episodes})){draft=fresh();}else{error.textContent='Chưa tạo được dự án. Hãy kiểm tra bộ nhớ trình duyệt và thử lại.';}};
}
export function episodeEditor(project){if(!project.episodes?.length)return '';return `<section class="card episode-editor"><h2>${project.seriesKind==='products'?'Các sản phẩm trong dự án':'Các tập trong dự án'} (${project.episodes.length})</h2><p>Tên và ý tưởng riêng được tự động lưu cùng dự án.</p>${episodeRows(project.episodes,'episode')}</section>`;}
export function bindEpisodeEditor(project,changed){document.querySelectorAll('[data-episode-title]').forEach(el=>el.oninput=e=>{project.episodes[Number(el.dataset.episodeTitle)].title=e.target.value;changed();});document.querySelectorAll('[data-episode-idea]').forEach(el=>el.oninput=e=>{project.episodes[Number(el.dataset.episodeIdea)].idea=e.target.value;changed();});}
