const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({name:'',notes:'',ratio:'9:16',seconds:'40',style:'Chân thực',kind:'series',images:[]});
let draft=fresh();
const episodeRows=(rows,prefix)=>rows.map((e,i)=>`<article class="episode-row"><strong>${i+1}</strong><div><label>Tên tập / sản phẩm ${i+1}<input maxlength="120" data-${prefix}-title="${i}" value="${escape(e.title)}" placeholder="Ví dụ: Tập ${i+1} hoặc tên sản phẩm"></label><label>Ý tưởng riêng ${i+1}<textarea maxlength="20000" data-${prefix}-idea="${i}" rows="3" placeholder="Nội dung dành riêng cho tập hoặc sản phẩm này">${escape(e.idea)}</textarea></label></div></article>`).join('');
export function textProjectForm(disabled){return `<form id="text-project-form" class="text-project-form"><h2>Tạo dự án mới</h2><label for="new-project-name">Tên dự án</label><input id="new-project-name" maxlength="120" required value="${escape(draft.name)}" placeholder="Đặt tên cho dự án của anh"><label for="new-project-idea">Nội dung ý tưởng dự án</label><textarea id="new-project-idea" maxlength="50000" rows="6" placeholder="Nhập câu chuyện, kịch bản hoặc ý tưởng tổng thể…">${escape(draft.notes)}</textarea><fieldset class="basic-settings"><legend>Cài đặt cơ bản</legend><div class="form-grid"><label>Khung hình<select id="new-project-ratio">${[['9:16','Dọc 9:16'],['16:9','Ngang 16:9'],['1:1','Vuông 1:1']].map(([v,t])=>`<option value="${v}" ${draft.ratio===v?'selected':''}>${t}</option>`).join('')}</select></label><label><span id="duration-label">Thời lượng mỗi tập / sản phẩm</span><select id="new-project-seconds">${[['8','8 giây'],['16','16 giây'],['40','40 giây'],['60','1 phút'],['120','2 phút'],['180','3 phút'],['300','5 phút']].map(([v,t])=>`<option value="${v}" ${draft.seconds===v?'selected':''}>${t}</option>`).join('')}</select></label><label>Phong cách video<select id="new-project-style">${['Chân thực','Điện ảnh','Hoạt hình 2D','Hoạt hình 3D','Anime','Tài liệu','Sang trọng','Tối giản'].map(v=>`<option ${draft.style===v?'selected':''}>${v}</option>`).join('')}</select></label></div><p>Thời lượng là mục tiêu để chia cảnh. Với dự án nhiều tập, cài đặt áp dụng chung cho từng tập hoặc sản phẩm.</p></fieldset><fieldset class="basic-settings"><legend>Ảnh nhân vật / sản phẩm tham chiếu</legend><p>Chọn tối đa 20 ảnh JPG, PNG hoặc WebP, mỗi ảnh tối đa 10 MB. Ảnh được lưu vào Nhân vật &amp; Bối cảnh khi tạo dự án.</p><label>Thêm ảnh<input id="new-reference-files" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><div id="new-reference-list" class="new-reference-list"></div></fieldset><fieldset class="basic-settings"><legend>Các tập trong dự án</legend><p>Bắt đầu với Tập 1. Khi cần, anh thêm tập tiếp theo ngay trong dự án; không cần chọn trước số tập.</p><label>Kiểu nội dung<select id="new-series-kind"><option value="series" ${draft.kind==='series'?'selected':''}>Phim / video nhiều tập</option><option value="products" ${draft.kind==='products'?'selected':''}>Nhóm sản phẩm</option></select></label></fieldset><p id="new-project-error" role="alert"></p><button class="primary" type="submit" ${disabled?'disabled':''}>Tạo dự án</button></form>`;}
export function bindTextProject(onCreate){
 const form=document.querySelector('#text-project-form');if(!form)return;
 form.querySelector('#new-project-name').oninput=e=>draft.name=e.target.value;
 form.querySelector('#new-project-idea').oninput=e=>draft.notes=e.target.value;
 for(const [id,key] of [['new-project-ratio','ratio'],['new-project-seconds','seconds'],['new-project-style','style']])form.querySelector('#'+id).onchange=e=>draft[key]=e.target.value;
 const error=form.querySelector('#new-project-error');
 const drawImages=()=>{const list=form.querySelector('#new-reference-list');list.innerHTML=draft.images.map((a,i)=>`<article class="new-reference-card"><img src="${a.url}" alt="${escape(a.name)}"><label>Tên ảnh<input data-reference-name="${i}" value="${escape(a.name)}" maxlength="120"></label><label>Loại ảnh<select data-reference-type="${i}"><option value="character" ${a.type==='character'?'selected':''}>Nhân vật</option><option value="product" ${a.type==='product'?'selected':''}>Sản phẩm</option></select></label><button type="button" data-reference-remove="${i}">Bỏ ảnh</button></article>`).join('');list.querySelectorAll('[data-reference-name]').forEach(el=>el.oninput=()=>draft.images[Number(el.dataset.referenceName)].name=el.value);list.querySelectorAll('[data-reference-type]').forEach(el=>el.onchange=()=>draft.images[Number(el.dataset.referenceType)].type=el.value);list.querySelectorAll('[data-reference-remove]').forEach(el=>el.onclick=()=>{URL.revokeObjectURL(draft.images.splice(Number(el.dataset.referenceRemove),1)[0].url);drawImages();});};
 form.querySelector('#new-reference-files').onchange=e=>{error.textContent='';for(const file of e.target.files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){error.textContent='Một số ảnh không đúng định dạng hoặc vượt quá 10 MB.';continue;}if(draft.images.length>=20){error.textContent='Tối đa 20 ảnh tham chiếu.';break;}draft.images.push({file,url:URL.createObjectURL(file),name:file.name.replace(/\.[^.]+$/,''),type:'character'});}e.target.value='';drawImages();};drawImages();
 form.querySelector('#new-series-kind').onchange=e=>draft.kind=e.target.value;
 form.onsubmit=async e=>{e.preventDefault();const error=form.querySelector('#new-project-error');if(!draft.name.trim()){error.textContent='Vui lòng nhập tên dự án.';return;}const episodes=[{id:crypto.randomUUID(),title:draft.kind==='products'?'Sản phẩm 1':'Tập 1',idea:'',status:'draft'}];const submit=form.querySelector('button[type="submit"]');submit.disabled=true;try{if(await onCreate({name:draft.name.trim(),notes:draft.notes,ratio:draft.ratio,seconds:Number(draft.seconds),style:draft.style,seriesKind:draft.kind,episodes},draft.images)){draft.images.forEach(a=>URL.revokeObjectURL(a.url));draft=fresh();}else{error.textContent='Chưa tạo được dự án. Hãy kiểm tra bộ nhớ trình duyệt và thử lại.';}}catch(err){error.textContent='Chưa tạo được dự án: '+err.message;}finally{submit.disabled=false;}};
}
export function episodeEditor(project){const e=project.episodes?.find(e=>e.id===project.activeEpisodeId);if(!e)return '';return `<section class="card episode-editor"><h2>Nội dung tập đang mở</h2><p>Ảnh tham chiếu dùng chung cho dự án. Kịch bản và video được lưu riêng theo từng tập.</p><label>Tên tập / sản phẩm<input id="episode-title" maxlength="120" value="${escape(e.title)}"></label><label>Ý tưởng riêng của tập<textarea id="episode-idea" maxlength="20000" rows="4">${escape(e.idea)}</textarea></label><p>Thay đổi ý tưởng không ghi đè các prompt đã chỉnh sửa.</p></section>`;}
export function bindEpisodeEditor(project,changed){const e=project.episodes?.find(e=>e.id===project.activeEpisodeId);if(!e)return;const title=document.querySelector('#episode-title'),idea=document.querySelector('#episode-idea');if(title)title.oninput=()=>{e.title=title.value;const b=document.querySelector(`[data-open-episode="${e.id}"] strong`);if(b)b.textContent=e.title||'Chưa đặt tên';changed();};if(idea)idea.oninput=()=>{e.idea=idea.value;changed();};}
