import {aiConfig,aiReady,aiRequest,blobData,dataBlob} from './ai-connection.js';
import {draftScenes} from './studio.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups=[['product','Sản phẩm'],['character','Nhân vật'],['context','Bối cảnh']];
const textGroups=groups.filter(([type])=>type!=='product');
export function prepareTextPrompts(p,assets){
 p.referencePrompts=textGroups.map(([type,label])=>({id:crypto.randomUUID(),type,required:type!=='product'||assets.some(a=>a.type===type)||p.seriesKind==='products',assetId:assets.find(a=>a.type===type)?.id||'',text:`Tạo ảnh tham chiếu ${label.toLowerCase()} cho dự án “${p.name}”. Ý tưởng: ${p.notes||'Bổ sung mô tả chi tiết tại đây'}. ${type==='product'?'Giữ nguyên hình dáng, màu sắc và nhãn theo ảnh sản phẩm gốc; không tự thêm đặc tính.':type==='character'?'Thiết kế nhân vật nhất quán về khuôn mặt, tóc, trang phục; mô tả rõ ngoại hình và tư thế.':'Mô tả rõ không gian, ánh sáng, bố cục và đạo cụ; giữ bối cảnh nhất quán giữa các cảnh.'} Phong cách: ${p.brand.style}. Khung hình ${p.product.ratio}. Không thêm chữ hoặc watermark.`}));
 const parts=p.episodes?.length?p.episodes:[{title:p.name,idea:p.notes}];
 p.prompts=parts.flatMap(e=>draftScenes({...p,prompts:[],product:{...p.product,idea:[p.notes,e.idea!==p.notes?e.idea:''].filter(Boolean).join('\n')}},assets).map(s=>({...s,episodeId:e.id||p.episodeId,title:parts.length>1?`${e.title} · ${s.title}`:s.title})));
}
export function textPromptsPage(p){return `<div class="page-head"><div><p class="eyebrow">PROMPT / CÂU LỆNH</p><h1>${esc(p.name)}</h1><p>Dự án đã lưu trong Các dự án gần đây. Chỉnh sửa prompt, hoàn thiện ảnh tham chiếu rồi tạo video.</p></div><button id="save-text-prompts" class="primary">Lưu câu lệnh</button></div><p id="status" role="status">Tự động lưu khi chỉnh sửa</p><div class="notice info">Prompt nháp được tạo theo mẫu từ thông tin dự án, chưa dùng AI. ${aiConfig().mode==='gemini'?'Đang chọn Gemini API. Cấu hình và kiểm tra máy chủ ở Cài đặt → Kết nối AI trước khi tạo ảnh/video.':'Tạo ảnh/video qua Flow ở tab riêng: sao chép prompt, chọn ảnh tham chiếu trên Flow và nhập kết quả về tool.'}</div><nav class="hub-tabs" role="tablist" aria-label="Nhóm câu lệnh">${[...textGroups,['script','Kịch bản']].map(([k,t])=>`<button type="button" role="tab" id="prompt-tab-${k}" data-prompt-tab="${k}" aria-controls="text-${k}" aria-selected="${k==='script'}" class="${k==='script'?'active':''}">Prompt ${t.toLowerCase()}</button>`).join('')}</nav><div id="text-reference-prompts"></div><section id="text-script" class="card" role="tabpanel" aria-labelledby="prompt-tab-script"><h2>Prompt kịch bản</h2><p>Mỗi cảnh có câu lệnh riêng để chỉnh sửa. Chỉ hiện nút tạo video sau khi đủ ảnh cho các nhóm được sử dụng.</p><p id="text-readiness" role="status"></p><button id="sync-text-refs" class="primary" hidden>Đồng bộ ảnh tham chiếu &amp; prompt kịch bản</button><p id="text-sync-result" role="status"></p>${p.prompts.map((s,i)=>`<article class="text-scene"><label>Tên cảnh ${i+1}<input data-text-scene-title="${s.id}" value="${esc(s.title)}"></label><label>Câu lệnh cảnh ${i+1} · ${s.duration||8} giây<textarea rows="6" data-text-scene="${s.id}">${esc(s.text)}</textarea></label><div class="scene-reference-choice" data-scene-refs="${s.id}"></div><div class="actions"><button data-text-copy-scene="${s.id}">Sao chép prompt</button>${aiConfig().mode==='gemini'?`<button class="primary text-create-video" data-text-video="${s.id}" hidden>${s.aiTicket?'Kiểm tra / nhận video':'Tạo video bằng Veo'}</button>`:`<a class="primary text-create-video" data-text-video="${s.id}" href="https://flow.google/" target="_blank" rel="noopener" hidden>Tạo video qua Flow ↗</a>`}</div></article>`).join('')}</section>`;}
export async function bindTextPrompts({project:p,db,changed,save,blobUrl,isCurrent,reportError,setBusy}){
 if(!p.referencePrompts){const assets=await db('list',null,'assets',p.id);if(!isCurrent())return true;const existing=p.prompts;prepareTextPrompts(p,assets);if(existing.length)p.prompts=existing;changed();save();return false;}
 const copy=async(text,b)=>{try{await navigator.clipboard.writeText(text);b.textContent='Đã sao chép';}catch{reportError(Error('Hãy chọn nội dung prompt và nhấn Ctrl+C.'));}};
 document.querySelector('#save-text-prompts').onclick=()=>save(true);
 document.querySelectorAll('[data-text-scene]').forEach(el=>el.oninput=()=>{p.prompts.find(s=>s.id===el.dataset.textScene).text=el.value;changed();readiness();});
 document.querySelectorAll('[data-text-scene-title]').forEach(el=>el.oninput=()=>{p.prompts.find(s=>s.id===el.dataset.textSceneTitle).title=el.value;changed();});
 document.querySelectorAll('[data-text-copy-scene]').forEach(el=>el.onclick=()=>copy(p.prompts.find(s=>s.id===el.dataset.textCopyScene).text,el));
 let selectedTab='script';
 const selectTab=key=>{selectedTab=key;document.querySelectorAll('[data-prompt-tab]').forEach(el=>{const active=el.dataset.promptTab===key;el.classList.toggle('active',active);el.setAttribute('aria-selected',String(active));});for(const type of ['character','context','script']){const panel=document.querySelector('#text-'+type);if(panel)panel.hidden=type!==key;}};
 document.querySelectorAll('[data-prompt-tab]').forEach(el=>el.onclick=()=>selectTab(el.dataset.promptTab));
 let assets=[];
 const defaultRefs=()=>p.referencePrompts.filter(r=>r.type!=='product'&&r.required).map(r=>assets.find(a=>a.id===r.assetId));
 const sceneRefs=s=>s.customReferences?(s.assetIds||[]).map(id=>assets.find(a=>a.id===id)):defaultRefs();
 const sceneReady=s=>{const refs=sceneRefs(s);return refs.length>0&&refs.every(Boolean);};
 function readiness(){const count=p.prompts.filter(sceneReady).length;document.querySelector('#text-readiness').textContent=`${count}/${p.prompts.length} cảnh đã đủ ảnh tham chiếu. Mỗi cảnh có thể chọn ảnh riêng từ thư viện chung.`;document.querySelector('#sync-text-refs').hidden=!count;document.querySelectorAll('[data-text-video]').forEach(el=>{const s=p.prompts.find(s=>s.id===el.dataset.textVideo);el.hidden=!sceneReady(s)||!s.text.trim();});}
 function syncReferences(){let count=0;for(const scene of p.prompts){if(!sceneReady(scene))continue;const refs=sceneRefs(scene),ids=[...new Set(refs.map(a=>a.id))],block='[ẢNH THAM CHIẾU]\n'+refs.map(a=>`${groups.find(g=>g[0]===a.type)?.[1]||'Ảnh'}: ${a.name}`).join('\n')+'\nGiữ nhất quán các ảnh đã chọn trong cảnh.\n[/ẢNH THAM CHIẾU]';scene.assetIds=ids;scene.text=scene.text.replace(/\n?\[ẢNH THAM CHIẾU\][\s\S]*?\[\/ẢNH THAM CHIẾU\]/g,'').trimEnd()+'\n'+block;count++;}if(!count)return false;document.querySelectorAll('[data-text-scene]').forEach(el=>el.value=p.prompts.find(s=>s.id===el.dataset.textScene).text);changed();if(!save())return false;document.querySelector('#text-sync-result').textContent=`Đã đồng bộ ảnh cho ${count} cảnh của tập đang mở. Ảnh chọn riêng cho từng cảnh được giữ nguyên.`;return true;}
 function drawSceneRefs(){document.querySelectorAll('[data-scene-refs]').forEach(box=>{const scene=p.prompts.find(s=>s.id===box.dataset.sceneRefs);box.innerHTML=`<label class="series-toggle"><input type="checkbox" data-custom-refs ${scene.customReferences?'checked':''}>Chọn ảnh riêng cho cảnh này</label>${scene.customReferences?`<div class="ref-options">${assets.map(a=>`<label><input type="checkbox" data-scene-image="${a.id}" ${(scene.assetIds||[]).includes(a.id)?'checked':''}><img src="${blobUrl(a.blob)}" alt=""><span>${esc(a.name)}</span></label>`).join('')||'<p>Thêm ảnh vào thư viện chung trước.</p>'}</div>`:'<p>Dùng các ảnh đã chọn ở tab Prompt nhân vật và Prompt bối cảnh.</p>'}`;box.querySelector('[data-custom-refs]').onchange=event=>{scene.customReferences=event.target.checked;if(scene.customReferences)scene.assetIds=defaultRefs().filter(Boolean).map(a=>a.id);changed();drawSceneRefs();readiness();selectTab(selectedTab);};box.querySelectorAll('[data-scene-image]').forEach(input=>input.onchange=()=>{scene.assetIds=[...box.querySelectorAll('[data-scene-image]:checked')].map(el=>el.dataset.sceneImage);changed();readiness();});});}
 document.querySelector('#sync-text-refs').onclick=syncReferences;
 document.querySelectorAll('[data-text-video]').forEach(el=>el.onclick=e=>{if(aiConfig().mode!=='gemini'){if(!syncReferences())return false;return;}e.preventDefault();runVideo(el);});
 async function runVideo(el){if(el.disabled)return;const scene=p.prompts.find(s=>s.id===el.dataset.textVideo),out=document.querySelector('#text-sync-result');el.disabled=true;setBusy(true);try{if(!aiReady())throw Error('Vào Cài đặt → Kết nối AI và kiểm tra kết nối trước.');if(!scene.aiTicket){if(!sceneReady(scene)||!syncReferences())return;if((scene.assetIds||[]).length>3)throw Error('Veo nhận tối đa 3 ảnh tham chiếu mỗi cảnh. Hãy chọn lại ảnh riêng cho cảnh.');if(scene.duration!==8||!['16:9','9:16'].includes(p.product.ratio))throw Error('Chế độ Veo với ảnh tham chiếu hiện nhận cảnh 8 giây, khung 16:9 hoặc 9:16. Hãy dùng Flow cho cảnh khác hoặc điều chỉnh dự án.');if(!confirm('Gửi câu lệnh và ảnh tham chiếu đến Gemini API để tạo 1 video 8 giây? Google có thể tính phí theo tài khoản API.'))return;out.textContent='Đang gửi yêu cầu tạo video…';const images=await Promise.all(assets.filter(a=>scene.assetIds.includes(a.id)).slice(0,3).map(a=>blobData(a.blob)));const d=await aiRequest('/video',{prompt:scene.text,images,ratio:p.product.ratio,seconds:8});if(!d.ticket)throw Error('Máy chủ chưa trả mã tác vụ.');scene.aiTicket=d.ticket;changed();save();el.textContent='Kiểm tra / nhận video';out.textContent='Đã gửi tác vụ. Chờ Google xử lý rồi bấm Kiểm tra / nhận video. Không bấm tạo lại.';return;}
 const d=await aiRequest('/jobs/'+encodeURIComponent(scene.aiTicket));if(!d.done){out.textContent='Google đang xử lý. Anh có thể kiểm tra lại sau.';return;}if(!d.data||d.mimeType!=='video/mp4')throw Error('Kết quả video không hợp lệ.');const id=crypto.randomUUID(),blob=dataBlob(d.data,d.mimeType);await db('put',{id,projectId:p.id,blob,name:scene.title+'.mp4',createdAt:Date.now()},'media');p.videos.push({id,promptId:scene.id,title:scene.title,fileName:scene.title+'.mp4',createdAt:Date.now()});delete scene.aiTicket;changed();save();el.textContent='Tạo video bằng Veo';out.textContent='Đã lưu video vào menu Video của dự án.';}catch(err){out.textContent=err.message;}finally{el.disabled=false;setBusy(false);}}

 async function draw(){assets=await db('list',null,'assets',p.id);if(!isCurrent())return;const box=document.querySelector('#text-reference-prompts');box.innerHTML=p.referencePrompts.filter(r=>r.type!=='product').map(r=>{const label=groups.find(g=>g[0]===r.type)[1],a=assets.find(a=>a.id===r.assetId);return `<section class="card" id="text-${r.type}" role="tabpanel" aria-labelledby="prompt-tab-${r.type}" ${selectedTab===r.type?'':'hidden'}><h2>Prompt ${label.toLowerCase()}</h2><label class="series-toggle"><input type="checkbox" data-ref-required="${r.id}" ${r.required?'checked':''}>Sử dụng ${label.toLowerCase()} trong video</label><label>Câu lệnh tạo ảnh<textarea rows="5" data-ref-prompt="${r.id}">${esc(r.text)}</textarea></label><div class="actions"><button data-ref-copy="${r.id}">Sao chép prompt</button>${aiConfig().mode==='gemini'?`<button data-ref-generate="${r.id}">Tạo ảnh bằng Gemini</button>`:`<a href="https://flow.google/" target="_blank" rel="noopener">Tạo ảnh tham chiếu qua Flow ↗</a>`}<label class="upload">Nhập ảnh kết quả<input data-ref-upload="${r.id}" type="file" accept="image/png,image/jpeg,image/webp" hidden></label></div><label>Chọn ảnh có sẵn<select data-ref-select="${r.id}"><option value="">Chưa chọn ảnh</option>${assets.filter(a=>a.type===r.type).map(a=>`<option value="${a.id}" ${a.id===r.assetId?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label>${a?`<div class="text-reference-preview"><img src="${blobUrl(a.blob)}" alt="${esc(a.name)}"><span>Đã có ảnh tham chiếu</span><a download="${esc(a.name)}" href="${blobUrl(a.blob)}">Tải ảnh để dùng trên Flow</a></div>`:'<p>Chưa có ảnh tham chiếu.</p>'}</section>`;}).join('');
 box.querySelectorAll('[data-ref-prompt]').forEach(el=>el.oninput=()=>{p.referencePrompts.find(r=>r.id===el.dataset.refPrompt).text=el.value;changed();});
 box.querySelectorAll('[data-ref-required]').forEach(el=>el.onchange=()=>{p.referencePrompts.find(r=>r.id===el.dataset.refRequired).required=el.checked;changed();readiness();});
 box.querySelectorAll('[data-ref-copy]').forEach(el=>el.onclick=()=>copy(p.referencePrompts.find(r=>r.id===el.dataset.refCopy).text,el));
 box.querySelectorAll('[data-ref-select]').forEach(el=>el.onchange=async()=>{p.referencePrompts.find(r=>r.id===el.dataset.refSelect).assetId=el.value;changed();save();await draw();});
 box.querySelectorAll('[data-ref-generate]').forEach(el=>el.onclick=async()=>{if(el.disabled)return;el.disabled=true;setBusy(true);try{if(!aiReady())throw Error('Vào Cài đặt → Kết nối AI và kiểm tra kết nối trước.');if(assets.length>=50)throw Error('Thư viện tối đa 50 ảnh.');const ref=p.referencePrompts.find(r=>r.id===el.dataset.refGenerate);if(!ref.text.trim())throw Error('Nhập prompt trước khi tạo ảnh.');if(!confirm('Gửi prompt và ảnh đang chọn đến Gemini API để tạo ảnh? Google có thể tính phí theo tài khoản API.'))return;el.textContent='Đang tạo ảnh…';const source=assets.find(a=>a.id===ref.assetId),d=await aiRequest('/image',{prompt:ref.text,images:source?[await blobData(source.blob)]:[]});if(!d.data||!['image/png','image/jpeg','image/webp'].includes(d.mimeType))throw Error('Máy chủ không trả ảnh hợp lệ.');const blob=dataBlob(d.data,d.mimeType),bitmap=await createImageBitmap(blob);bitmap.close();const a={id:crypto.randomUUID(),projectId:p.id,name:groups.find(g=>g[0]===ref.type)[1]+' AI '+new Date().toLocaleTimeString('vi-VN'),type:ref.type,blob,createdAt:Date.now()};await db('put',a);ref.assetId=a.id;changed();save();await draw();}catch(err){reportError(err);}finally{setBusy(false);el.disabled=false;el.textContent='Tạo ảnh bằng Gemini';}});
 box.querySelectorAll('[data-ref-upload]').forEach(el=>el.onchange=async()=>{const file=el.files[0];if(!file)return;setBusy(true);el.disabled=true;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('Chọn ảnh PNG, JPG hoặc WebP tối đa 10 MB.');const bitmap=await createImageBitmap(file);bitmap.close();if(assets.length>=50)throw Error('Thư viện tối đa 50 ảnh.');const ref=p.referencePrompts.find(r=>r.id===el.dataset.refUpload),a={id:crypto.randomUUID(),projectId:p.id,name:file.name,type:ref.type,blob:file,createdAt:Date.now()};await db('put',a);ref.assetId=a.id;changed();save();await draw();}catch(e){reportError(e);}finally{setBusy(false);el.disabled=false;el.value='';}});drawSceneRefs();readiness();selectTab(selectedTab);}
 await draw();return true;
}
