const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({name:'',notes:'',ratio:'9:16',seconds:'40',style:'Chân thực',kind:'series',structure:'single',images:[],episode:{title:'Tập 1',idea:'',ratio:'9:16',seconds:'40',style:'Chân thực',images:[]}});
let draft=fresh();
const options=(values,current)=>values.map(([v,t])=>`<option value="${v}" ${String(current)===v?'selected':''}>${t}</option>`).join('');
const ratios=[['9:16','Dọc 9:16'],['16:9','Ngang 16:9'],['1:1','Vuông 1:1']];
const durations=[['8','8 giây'],['16','16 giây'],['40','40 giây'],['60','1 phút'],['120','2 phút'],['180','3 phút'],['300','5 phút']];
const styles=['Chân thực','Điện ảnh','Hoạt hình 2D','Hoạt hình 3D','Anime','Tài liệu','Sang trọng','Tối giản'].map(v=>[v,v]);
export function basicEpisodeFields(prefix,values){return `<fieldset class="basic-settings"><legend>Cài đặt cơ bản của tập</legend><div class="form-grid"><label>Khung hình của tập<select id="${prefix}-ratio">${options(ratios,values.ratio)}</select></label><label>Thời lượng của tập<select id="${prefix}-seconds">${options(durations,values.seconds)}</select></label><label>Phong cách video của tập<select id="${prefix}-style">${options(styles,values.style)}</select></label></div></fieldset>`;}
const imageFields=(prefix,label)=>`<fieldset class="basic-settings"><legend>${label}</legend><p>Tối đa 20 ảnh JPG, PNG hoặc WebP, mỗi ảnh tối đa 10 MB.</p><label>Thêm ảnh<input id="${prefix}-files" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><div id="${prefix}-list" class="new-reference-list"></div></fieldset>`;
export function bindDraftImages(container,prefix,images,error){const list=container.querySelector('#'+prefix+'-list');const draw=()=>{list.innerHTML=images.map((a,i)=>`<article class="new-reference-card"><img src="${a.url}" alt="${escape(a.name)}"><label>Tên ảnh<input data-reference-name="${i}" value="${escape(a.name)}" maxlength="120"></label><label>Loại ảnh<select data-reference-type="${i}">${options([['character','Nhân vật'],['product','Sản phẩm'],['context','Bối cảnh']],a.type)}</select></label><button type="button" data-reference-remove="${i}">Bỏ ảnh</button></article>`).join('');list.querySelectorAll('[data-reference-name]').forEach(el=>el.oninput=()=>images[Number(el.dataset.referenceName)].name=el.value);list.querySelectorAll('[data-reference-type]').forEach(el=>el.onchange=()=>images[Number(el.dataset.referenceType)].type=el.value);list.querySelectorAll('[data-reference-remove]').forEach(el=>el.onclick=()=>{URL.revokeObjectURL(images.splice(Number(el.dataset.referenceRemove),1)[0].url);draw();});};container.querySelector('#'+prefix+'-files').onchange=event=>{error.textContent='';for(const file of event.target.files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){error.textContent='Một số ảnh không đúng định dạng hoặc vượt quá 10 MB.';continue;}if(images.length>=20){error.textContent='Tối đa 20 ảnh tham chiếu.';break;}images.push({file,url:URL.createObjectURL(file),name:file.name.replace(/\.[^.]+$/,''),type:'character'});}event.target.value='';draw();};draw();}
export function textProjectForm(disabled){return `<form id="text-project-form" class="text-project-form"><h2>Tạo dự án mới</h2><label for="new-project-name">Tên dự án</label><input id="new-project-name" maxlength="120" required value="${escape(draft.name)}" placeholder="Đặt tên cho dự án của anh"><div id="project-idea-fields" ${draft.structure==='multiple'?'hidden':''}><label for="new-project-idea">Nội dung ý tưởng dự án</label><textarea id="new-project-idea" maxlength="50000" rows="6" placeholder="Nhập câu chuyện, kịch bản hoặc ý tưởng tổng thể…">${escape(draft.notes)}</textarea></div><fieldset class="basic-settings"><legend>Cài đặt cơ bản</legend><div class="form-grid"><label>Khung hình<select id="new-project-ratio">${options(ratios,draft.ratio)}</select></label><div class="duration-structure"><label>Thời lượng dự án<select id="new-project-seconds">${options(durations,draft.seconds)}</select></label><label>Loại dự án<select id="new-project-structure"><option value="single" ${draft.structure==='single'?'selected':''}>1 tập</option><option value="multiple" ${draft.structure==='multiple'?'selected':''}>Nhiều tập</option></select></label></div><label>Phong cách video<select id="new-project-style">${options(styles,draft.style)}</select></label></div><p id="project-settings-hint">${draft.structure==='multiple'?'Cài đặt mặc định cho các tập mới. Mỗi tập có thể điều chỉnh riêng; tổng thời lượng dự án tăng khi thêm tập.':'Cài đặt áp dụng cho toàn bộ video của dự án.'}</p></fieldset><div id="project-image-fields" ${draft.structure==='multiple'?'hidden':''}>${imageFields('new-reference','Ảnh nhân vật / sản phẩm của dự án')}</div><section id="first-episode-fields" class="card first-episode" ${draft.structure==='multiple'?'':'hidden'}><h2>Tập 1</h2><p>Chỉ tạo tập đầu tiên. Anh thêm tập tiếp theo khi cần, không phải chọn trước số tập.</p><label>Tên tập 1<input id="new-episode-title" maxlength="120" value="${escape(draft.episode.title)}"></label><label>Nội dung ý tưởng của tập 1<textarea id="new-episode-idea" maxlength="20000" rows="5">${escape(draft.episode.idea)}</textarea></label>${basicEpisodeFields('new-episode',draft.episode)}${imageFields('episode-reference','Ảnh nhân vật / sản phẩm của tập 1')}<p>Ảnh được lưu trong thư viện chung của dự án và chọn làm tham chiếu cho tập này.</p><label>Kiểu nội dung<select id="new-series-kind"><option value="series" ${draft.kind==='series'?'selected':''}>Phim / video nhiều tập</option><option value="products" ${draft.kind==='products'?'selected':''}>Nhóm sản phẩm</option></select></label></section><p id="new-project-error" role="alert"></p><button class="primary" type="submit" ${disabled?'disabled':''}>Tạo dự án</button></form>`;}
export function bindTextProject(onCreate){
 const form=document.querySelector('#text-project-form');if(!form)return;const error=form.querySelector('#new-project-error');
 form.querySelector('#new-project-name').oninput=e=>draft.name=e.target.value;
 form.querySelector('#new-project-idea').oninput=e=>draft.notes=e.target.value;
 for(const key of ['ratio','seconds','style']){form.querySelector('#new-project-'+key).onchange=e=>draft[key]=e.target.value;form.querySelector('#new-episode-'+key).onchange=e=>draft.episode[key]=e.target.value;}
 form.querySelector('#new-episode-title').oninput=e=>draft.episode.title=e.target.value;
 form.querySelector('#new-episode-idea').oninput=e=>draft.episode.idea=e.target.value;
 const updateMode=()=>{const multiple=draft.structure==='multiple';form.querySelector('#first-episode-fields').hidden=!multiple;form.querySelector('#project-idea-fields').hidden=multiple;form.querySelector('#project-image-fields').hidden=multiple;form.querySelector('#new-episode-title').required=multiple;form.querySelector('#project-settings-hint').textContent=multiple?'Cài đặt mặc định cho các tập mới. Mỗi tập có thể điều chỉnh riêng; tổng thời lượng dự án tăng khi thêm tập.':'Cài đặt áp dụng cho toàn bộ video của dự án.';};
 form.querySelector('#new-project-structure').onchange=e=>{draft.structure=e.target.value;updateMode();};updateMode();
 bindDraftImages(form,'new-reference',draft.images,error);bindDraftImages(form,'episode-reference',draft.episode.images,error);
 form.querySelector('#new-series-kind').onchange=e=>draft.kind=e.target.value;
 form.onsubmit=async event=>{event.preventDefault();if(!draft.name.trim()){error.textContent='Vui lòng nhập tên dự án.';return;}const multiple=draft.structure==='multiple';if(multiple&&!draft.episode.title.trim()){error.textContent='Vui lòng nhập tên tập 1.';return;}const episodes=[{id:crypto.randomUUID(),title:multiple?draft.episode.title.trim():draft.name.trim(),idea:multiple?draft.episode.idea:'',status:'draft',...(multiple?{settings:{ratio:draft.episode.ratio,seconds:Number(draft.episode.seconds),style:draft.episode.style}}:{})}];const button=form.querySelector('[type="submit"]');button.disabled=true;try{if(await onCreate({name:draft.name.trim(),notes:multiple?'':draft.notes,ratio:draft.ratio,seconds:Number(draft.seconds),style:draft.style,projectStructure:draft.structure,seriesKind:multiple?draft.kind:'single',episodes},multiple?draft.episode.images:draft.images)){[...draft.images,...draft.episode.images].forEach(a=>URL.revokeObjectURL(a.url));draft=fresh();}else error.textContent='Chưa tạo được dự án. Hãy kiểm tra bộ nhớ trình duyệt và thử lại.';}catch(err){error.textContent='Chưa tạo được dự án: '+err.message;}finally{button.disabled=false;}};
}
export function episodeEditor(project){const e=project.episodes?.find(e=>e.id===project.activeEpisodeId);if(!e||project.projectStructure==='single')return '';return `<section class="card episode-editor"><h2>Nội dung tập đang mở</h2><p>Ảnh tham chiếu dùng chung cho dự án. Kịch bản và video được lưu riêng theo từng tập.</p><label>Tên tập / sản phẩm<input id="episode-title" maxlength="120" value="${escape(e.title)}"></label><label>Ý tưởng riêng của tập<textarea id="episode-idea" maxlength="20000" rows="4">${escape(e.idea)}</textarea></label><p>Thay đổi ý tưởng không ghi đè các prompt đã chỉnh sửa.</p></section>`;}
export function bindEpisodeEditor(project,changed){const e=project.episodes?.find(e=>e.id===project.activeEpisodeId);if(!e)return;const title=document.querySelector('#episode-title'),idea=document.querySelector('#episode-idea');if(title)title.oninput=()=>{e.title=title.value;const b=document.querySelector(`[data-open-episode="${e.id}"] strong`);if(b)b.textContent=e.title||'Chưa đặt tên';changed();};if(idea)idea.oninput=()=>{e.idea=idea.value;changed();};}
