import {draftScenes} from './studio.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups=[['product','Sản phẩm'],['character','Nhân vật'],['context','Bối cảnh']];
export function prepareTextPrompts(p,assets){
 p.referencePrompts=groups.map(([type,label])=>({id:crypto.randomUUID(),type,required:type!=='product'||assets.some(a=>a.type===type)||p.seriesKind==='products',assetId:assets.find(a=>a.type===type)?.id||'',text:`Tạo ảnh tham chiếu ${label.toLowerCase()} cho dự án “${p.name}”. Ý tưởng: ${p.notes||'Bổ sung mô tả chi tiết tại đây'}. ${type==='product'?'Giữ nguyên hình dáng, màu sắc và nhãn theo ảnh sản phẩm gốc; không tự thêm đặc tính.':type==='character'?'Thiết kế nhân vật nhất quán về khuôn mặt, tóc, trang phục; mô tả rõ ngoại hình và tư thế.':'Mô tả rõ không gian, ánh sáng, bố cục và đạo cụ; giữ bối cảnh nhất quán giữa các cảnh.'} Phong cách: ${p.brand.style}. Khung hình ${p.product.ratio}. Không thêm chữ hoặc watermark.`}));
 const parts=p.episodes?.length?p.episodes:[{title:p.name,idea:p.notes}];
 p.prompts=parts.flatMap(e=>draftScenes({...p,prompts:[],product:{...p.product,idea:[p.notes,e.idea!==p.notes?e.idea:''].filter(Boolean).join('\n')}},assets).map(s=>({...s,title:parts.length>1?`${e.title} · ${s.title}`:s.title})));
}
export function textPromptsPage(p){return `<div class="page-head"><div><p class="eyebrow">PROMPT / CÂU LỆNH</p><h1>${esc(p.name)}</h1><p>Dự án đã lưu trong Các dự án gần đây. Chỉnh sửa prompt, hoàn thiện ảnh tham chiếu rồi tạo video.</p></div><button id="save-text-prompts" class="primary">Lưu câu lệnh</button></div><p id="status" role="status">Tự động lưu khi chỉnh sửa</p><div class="notice info">Prompt nháp được tạo theo mẫu từ thông tin dự án, chưa dùng AI. Tạo ảnh/video qua Flow ở tab riêng: sao chép prompt, chọn ảnh tham chiếu trên Flow và nhập kết quả về tool.</div><nav class="hub-tabs" aria-label="Nhóm câu lệnh">${[...groups,['script','Kịch bản']].map(([k,t])=>`<a href="#text-${k}">Prompt ${t.toLowerCase()}</a>`).join('')}</nav><div id="text-reference-prompts"></div><section id="text-script" class="card"><h2>Prompt kịch bản</h2><p>Mỗi cảnh có câu lệnh riêng để chỉnh sửa. Chỉ hiện nút tạo video sau khi đủ ảnh cho các nhóm được sử dụng.</p><p id="text-readiness" role="status"></p>${p.prompts.map((s,i)=>`<article class="text-scene"><label>Tên cảnh ${i+1}<input data-text-scene-title="${s.id}" value="${esc(s.title)}"></label><label>Câu lệnh cảnh ${i+1} · ${s.duration||8} giây<textarea rows="6" data-text-scene="${s.id}">${esc(s.text)}</textarea></label><div class="actions"><button data-text-copy-scene="${s.id}">Sao chép prompt</button><a class="primary text-create-video" data-text-video="${s.id}" href="https://flow.google/" target="_blank" rel="noopener" hidden>Tạo video qua Flow ↗</a></div></article>`).join('')}</section>`;}
export async function bindTextPrompts({project:p,db,changed,save,blobUrl,isCurrent,reportError,setBusy}){
 if(!p.referencePrompts){const assets=await db('list',null,'assets',p.id);if(!isCurrent())return true;const existing=p.prompts;prepareTextPrompts(p,assets);if(existing.length)p.prompts=existing;changed();save();return false;}
 const copy=async(text,b)=>{try{await navigator.clipboard.writeText(text);b.textContent='Đã sao chép';}catch{reportError(Error('Hãy chọn nội dung prompt và nhấn Ctrl+C.'));}};
 document.querySelector('#save-text-prompts').onclick=()=>save(true);
 document.querySelectorAll('[data-text-scene]').forEach(el=>el.oninput=()=>{p.prompts.find(s=>s.id===el.dataset.textScene).text=el.value;changed();readiness();});
 document.querySelectorAll('[data-text-scene-title]').forEach(el=>el.oninput=()=>{p.prompts.find(s=>s.id===el.dataset.textSceneTitle).title=el.value;changed();});
 document.querySelectorAll('[data-text-copy-scene]').forEach(el=>el.onclick=()=>copy(p.prompts.find(s=>s.id===el.dataset.textCopyScene).text,el));
 let assets=[];
 const ready=()=>p.referencePrompts.some(r=>r.required)&&p.referencePrompts.filter(r=>r.required).every(r=>assets.some(a=>a.id===r.assetId));
 function readiness(){const ok=ready(),required=p.referencePrompts.filter(r=>r.required),missing=required.filter(r=>!assets.some(a=>a.id===r.assetId));document.querySelector('#text-readiness').textContent=ok?'Đủ ảnh tham chiếu. Sao chép prompt và tải các ảnh đã chọn lên Flow để tạo video.':required.length?`Cần hoàn thiện ảnh: ${missing.map(r=>groups.find(g=>g[0]===r.type)[1]).join(', ')}.`:'Chọn ít nhất một nhóm tham chiếu và thêm ảnh trước khi tạo video.';document.querySelectorAll('[data-text-video]').forEach(el=>el.hidden=!ok||!p.prompts.find(s=>s.id===el.dataset.textVideo).text.trim());}
 document.querySelectorAll('[data-text-video]').forEach(el=>el.onclick=()=>{if(!ready()||!save())return false;});
 async function draw(){assets=await db('list',null,'assets',p.id);if(!isCurrent())return;const box=document.querySelector('#text-reference-prompts');box.innerHTML=p.referencePrompts.map(r=>{const label=groups.find(g=>g[0]===r.type)[1],a=assets.find(a=>a.id===r.assetId);return `<section class="card" id="text-${r.type}"><h2>Prompt ${label.toLowerCase()}</h2><label class="series-toggle"><input type="checkbox" data-ref-required="${r.id}" ${r.required?'checked':''}>Sử dụng ${label.toLowerCase()} trong video</label><label>Câu lệnh tạo ảnh<textarea rows="5" data-ref-prompt="${r.id}">${esc(r.text)}</textarea></label><div class="actions"><button data-ref-copy="${r.id}">Sao chép prompt</button><a href="https://flow.google/" target="_blank" rel="noopener">Tạo ảnh tham chiếu qua Flow ↗</a><label class="upload">Nhập ảnh kết quả<input data-ref-upload="${r.id}" type="file" accept="image/png,image/jpeg,image/webp" hidden></label></div><label>Chọn ảnh có sẵn<select data-ref-select="${r.id}"><option value="">Chưa chọn ảnh</option>${assets.filter(a=>a.type===r.type).map(a=>`<option value="${a.id}" ${a.id===r.assetId?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label>${a?`<div class="text-reference-preview"><img src="${blobUrl(a.blob)}" alt="${esc(a.name)}"><span>Đã có ảnh tham chiếu</span><a download="${esc(a.name)}" href="${blobUrl(a.blob)}">Tải ảnh để dùng trên Flow</a></div>`:'<p>Chưa có ảnh tham chiếu.</p>'}</section>`;}).join('');
 box.querySelectorAll('[data-ref-prompt]').forEach(el=>el.oninput=()=>{p.referencePrompts.find(r=>r.id===el.dataset.refPrompt).text=el.value;changed();});
 box.querySelectorAll('[data-ref-required]').forEach(el=>el.onchange=()=>{p.referencePrompts.find(r=>r.id===el.dataset.refRequired).required=el.checked;changed();readiness();});
 box.querySelectorAll('[data-ref-copy]').forEach(el=>el.onclick=()=>copy(p.referencePrompts.find(r=>r.id===el.dataset.refCopy).text,el));
 box.querySelectorAll('[data-ref-select]').forEach(el=>el.onchange=async()=>{p.referencePrompts.find(r=>r.id===el.dataset.refSelect).assetId=el.value;changed();save();await draw();});
 box.querySelectorAll('[data-ref-upload]').forEach(el=>el.onchange=async()=>{const file=el.files[0];if(!file)return;setBusy(true);el.disabled=true;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('Chọn ảnh PNG, JPG hoặc WebP tối đa 10 MB.');const bitmap=await createImageBitmap(file);bitmap.close();if(assets.length>=50)throw Error('Thư viện tối đa 50 ảnh.');const ref=p.referencePrompts.find(r=>r.id===el.dataset.refUpload),a={id:crypto.randomUUID(),projectId:p.id,name:file.name,type:ref.type,blob:file,createdAt:Date.now()};await db('put',a);ref.assetId=a.id;changed();save();await draw();}catch(e){reportError(e);}finally{setBusy(false);el.disabled=false;el.value='';}});readiness();}
 await draw();return true;
}
